/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acbr.Reinf.demo;

import com.acbr.ACBrSessao;
import com.acbr.reinf.ACBrReinf;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.text.DateFormat;  
import java.util.Calendar;  


/**
 *
 * @author rften
 */
public class FrmMain extends javax.swing.JFrame {

    private ACBrReinf acbrReinf;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        try {
            acbrReinf = new ACBrReinf();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtbRespostas = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        btnCriarEvento = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnConsultarProt = new javax.swing.JButton();
        btnCriarEnviar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSetIDContribuinte = new javax.swing.JButton();
        btnSetIDTransmissor = new javax.swing.JButton();
        btnSetTipoContribuinte = new javax.swing.JButton();
        btnSetVersaoDF = new javax.swing.JButton();
        btnCarregarXMLEvento = new javax.swing.JButton();
        btnConsultarRecibo = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        ckbAtualizarXML = new javax.swing.JPanel();
        ckbAttXML = new javax.swing.JCheckBox();
        ckbExibirErroSchema = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtFormatoAlerta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbFormaEmissao = new javax.swing.JComboBox<>();
        ckbRetirarAcentos = new javax.swing.JCheckBox();
        ckbSalvar = new javax.swing.JCheckBox();
        txtLogs = new javax.swing.JTextField();
        btnSelectLog = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSchemaPath = new javax.swing.JTextField();
        btnSelectSchema = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        cmbUfDestino = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        cmbSSlType = new javax.swing.JComboBox<>();
        nudTimeOut = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        rdbHomologacao = new javax.swing.JRadioButton();
        rdbProducao = new javax.swing.JRadioButton();
        ckbVisualizar = new javax.swing.JCheckBox();
        ckbSalvarSOAP = new javax.swing.JCheckBox();
        jPanel22 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        txtProxyServidor = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        nudProxyPorta = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        txtProxyUsuario = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtProxySenha = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        ckbAjustarAut = new javax.swing.JCheckBox();
        jLabel43 = new javax.swing.JLabel();
        nudAguardar = new javax.swing.JSpinner();
        jLabel44 = new javax.swing.JLabel();
        nudTentativas = new javax.swing.JSpinner();
        jLabel45 = new javax.swing.JLabel();
        nudIntervalos = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cmbCrypt = new javax.swing.JComboBox<>();
        cmbHttp = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cmbXmlSign = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtCertPath = new javax.swing.JTextField();
        btnSelecionarCertificado = new javax.swing.JButton();
        txtDadosPFX = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtCertNumero = new javax.swing.JTextField();
        txtCertPassword = new javax.swing.JPasswordField();
        btnObterCertificados1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        ckbSalvarArqs = new javax.swing.JCheckBox();
        ckbPastaMensal = new javax.swing.JCheckBox();
        ckbAdicionaLiteral = new javax.swing.JCheckBox();
        ckbEmissaoPath = new javax.swing.JCheckBox();
        ckbSalvaPathEvento = new javax.swing.JCheckBox();
        ckbSepararPorCNPJ = new javax.swing.JCheckBox();
        ckbSepararPorModelo = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        txtArq = new javax.swing.JTextField();
        btnArq = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtContribuinte = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTransmissor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbTipoContribuinte = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbVersaoDF = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnCarregarConfiguracoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACBrLibReinf Demo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(744, 588));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Respostas"));

        rtbRespostas.setColumns(20);
        rtbRespostas.setRows(5);
        jScrollPane1.setViewportView(rtbRespostas);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTabbedPane2.setToolTipText("");
        jTabbedPane2.setName("Envio"); // NOI18N

        btnCriarEvento.setText("Criar Evento Reinf");
        btnCriarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEventoActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar Reinf");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnConsultarProt.setText("Consultar Reinf (prot.)");
        btnConsultarProt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProtActionPerformed(evt);
            }
        });

        btnCriarEnviar.setText("Criar Enviar Reinf");
        btnCriarEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEnviarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar Reinf");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSetIDContribuinte.setText("SetIDContribuinte");
        btnSetIDContribuinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetIDContribuinteActionPerformed(evt);
            }
        });

        btnSetIDTransmissor.setText("SetIDTransmissor");
        btnSetIDTransmissor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetIDTransmissorActionPerformed(evt);
            }
        });

        btnSetTipoContribuinte.setText("SetTipoContribuinte");
        btnSetTipoContribuinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetTipoContribuinteActionPerformed(evt);
            }
        });

        btnSetVersaoDF.setText("SetVersaoDF");
        btnSetVersaoDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetVersaoDFActionPerformed(evt);
            }
        });

        btnCarregarXMLEvento.setText("Carregar XML Evento Reinf");
        btnCarregarXMLEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarXMLEventoActionPerformed(evt);
            }
        });

        btnConsultarRecibo.setText("Consultar Recibo");
        btnConsultarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarReciboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarProt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCriarEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCriarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSetIDTransmissor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSetIDContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarregarXMLEvento))
                    .addComponent(btnSetVersaoDF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetTipoContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetIDContribuinte)
                    .addComponent(btnCarregarXMLEvento)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetIDTransmissor)
                    .addComponent(btnCriarEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetTipoContribuinte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarEnviar)
                    .addComponent(btnSetVersaoDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarProt)
                    .addComponent(btnConsultarRecibo))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Comandos", jPanel14);

        ckbAttXML.setText("Atualizar XML Cancelado");

        ckbExibirErroSchema.setText("Exibir Erro Schema");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Formato Alerta");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Forma de Emissão");

        cmbFormaEmissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "teNormal", "teContingencia", "teSVCAN", "teDPEC", "teFSDA", "teSCAN", "teSVCRS", "teSVCSP", "teOffLine" }));
        cmbFormaEmissao.setToolTipText("");

        ckbRetirarAcentos.setText("Retirar Acentos dos XMLs enviados");

        ckbSalvar.setText("Salvar Arquivos de Envio e Resposta");

        btnSelectLog.setText("btnSelectLog");
        btnSelectLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectLogActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Pasta dos Logs");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Pasta dos Schemas");

        btnSelectSchema.setText("jButton1");
        btnSelectSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSchemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ckbAtualizarXMLLayout = new javax.swing.GroupLayout(ckbAtualizarXML);
        ckbAtualizarXML.setLayout(ckbAtualizarXMLLayout);
        ckbAtualizarXMLLayout.setHorizontalGroup(
            ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFormatoAlerta)
                    .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                        .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtLogs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectLog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                        .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSchemaPath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectSchema, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                        .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(ckbAttXML)
                            .addComponent(ckbExibirErroSchema)
                            .addComponent(jLabel7)
                            .addComponent(cmbFormaEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbSalvar)
                            .addComponent(ckbRetirarAcentos))
                        .addGap(0, 173, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ckbAtualizarXMLLayout.setVerticalGroup(
            ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckbAttXML)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbExibirErroSchema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFormatoAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFormaEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ckbRetirarAcentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSchemaPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectSchema))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Geral", ckbAtualizarXML);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Uf Destino");

        cmbUfDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("SSL Type");

        cmbSSlType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LT_all", "LT_SSLv2", "LT_SSLv3", "LT_TSLv1", "LT_TSLv1_1", "LT_TSLv1_2", "LT_SSHv2" }));

        nudTimeOut.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("TimeOut");

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ambiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel20.setToolTipText("Ambiente");
        jPanel20.setFocusCycleRoot(true);
        jPanel20.setName("Ambiente"); // NOI18N

        buttonGroup1.add(rdbHomologacao);
        rdbHomologacao.setLabel("Homologação");

        buttonGroup1.add(rdbProducao);
        rdbProducao.setText("Produção");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbHomologacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbProducao)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbProducao)
                    .addComponent(rdbHomologacao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rdbProducao.getAccessibleContext().setAccessibleDescription("");

        ckbVisualizar.setLabel("Visualizar Mensagem");

        ckbSalvarSOAP.setText("Salvar envelope SOAP");

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proxy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel22.setToolTipText("Proxy");
        jPanel22.setName("Ambiente"); // NOI18N

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Servidor");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("Porta");

        nudProxyPorta.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Usuário");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("Senha");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProxyUsuario)
                    .addComponent(txtProxySenha)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProxyServidor)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(nudProxyPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProxyServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nudProxyPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProxyUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProxySenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retorno de Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        ckbAjustarAut.setText("Ajustar Automaticamente prop. \"Aguardar\"");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel43.setText("Aguardar");

        nudAguardar.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Tentativas");

        nudTentativas.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setText("Intervalo");

        nudIntervalos.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nudAguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nudTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nudIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ckbAjustarAut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckbAjustarAut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nudAguardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nudTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nudIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckbSalvarSOAP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbVisualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(cmbUfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(cmbSSlType, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nudTimeOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 121, Short.MAX_VALUE))
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nudTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSSlType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSalvarSOAP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("WebServices", jPanel6);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("CryptLib");

        cmbCrypt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cryNone", "cryOpenSSL", "cryCapicom", "cryWinCrypt" }));

        cmbHttp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "httpNone", "httpWinINet", "httpWinHttp", "httpOpenSSL", "httpIndy", " ", " ", " " }));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("HttpLib");

        cmbXmlSign.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "xsNone", "xsXmlSec", "xsMsXml", "xsMsXmlCapicom", "xsLibXml2" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("XmlSignLib");

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Certificados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel19.setToolTipText("Certificados");
        jPanel19.setName("DANFe"); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Caminho PFX");

        btnSelecionarCertificado.setText("btnSelectLog");
        btnSelecionarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarCertificadoActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Dados PFX");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Senha");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Número de Série");

        txtCertPassword.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtCertPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionarCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtCertNumero)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(0, 281, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(txtCertPassword)
            .addComponent(txtDadosPFX)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCertPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarCertificado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDadosPFX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(1, 1, 1)
                .addComponent(txtCertPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCertNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnObterCertificados1.setActionCommand("Obter Certificados");
        btnObterCertificados1.setLabel("Obter Certificados");
        btnObterCertificados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObterCertificados1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel17)
                                .addComponent(jLabel26)
                                .addComponent(cmbHttp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbCrypt, 0, 163, Short.MAX_VALUE)
                                .addComponent(jLabel27)
                                .addComponent(cmbXmlSign, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnObterCertificados1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(1, 1, 1)
                .addComponent(cmbCrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbHttp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbXmlSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObterCertificados1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Certificados", jPanel7);

        ckbSalvarArqs.setLabel("Salvar Arquivos em Pastas Separadas");

        ckbPastaMensal.setLabel("Criar Pastas Mensalmente");

        ckbAdicionaLiteral.setLabel("Adicionar Literal no nome das pastas");

        ckbEmissaoPath.setText("Salvar Documento pelo campo Data de Emissão");

        ckbSalvaPathEvento.setText("Salvar Arquivos de Eventos");

        ckbSepararPorCNPJ.setText("Separar Arqs pelo CNPJ do Certificado");

        ckbSepararPorModelo.setText("Separar Arqs pelo Modelo do Documento");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Pasta Arquivos Reinf");

        btnArq.setText("btnSelectLog");
        btnArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 233, Short.MAX_VALUE))
                            .addComponent(txtArq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArq, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbSalvarArqs)
                            .addComponent(ckbPastaMensal)
                            .addComponent(ckbAdicionaLiteral)
                            .addComponent(ckbEmissaoPath)
                            .addComponent(ckbSalvaPathEvento)
                            .addComponent(ckbSepararPorCNPJ)
                            .addComponent(ckbSepararPorModelo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(ckbSalvarArqs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbPastaMensal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbAdicionaLiteral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbEmissaoPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSalvaPathEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSepararPorCNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSepararPorModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArq))
                .addGap(0, 220, Short.MAX_VALUE))
        );

        ckbEmissaoPath.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane3.addTab("Arquivos", jPanel9);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("CNPJ ou CPF do Contribuinte");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("CNPJ ou CPF do Transmissor");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tipo de Contribuinte");

        cmbTipoContribuinte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tePessoaJuridica", "teOrgaoPublico", "tePessoaFisica" }));
        cmbTipoContribuinte.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Versão DF");

        cmbVersaoDF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1_03_00", "1_03_02", "1_04_00", "1_05_00", "1_05_01", "2_01_01", "2_01_02", " " }));
        cmbVersaoDF.setSelectedIndex(6);
        cmbVersaoDF.setToolTipText("");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTransmissor)
                            .addComponent(txtContribuinte)
                            .addComponent(cmbTipoContribuinte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbVersaoDF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel15))
                                .addGap(0, 193, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTransmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbVersaoDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Emitente", jPanel15);

        btnSalvar.setText("Salvar Configurações");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCarregarConfiguracoes.setLabel("Carregar Configurações");
        btnCarregarConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarConfiguracoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCarregarConfiguracoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCarregarConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        btnCarregarConfiguracoes.getAccessibleContext().setAccessibleName("Salvar Carregar Configurações");

        jTabbedPane1.addTab("Configurações", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addGap(49, 49, 49))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Envio");

        setSize(new java.awt.Dimension(900, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            // Altera as config de log
            Path pathLog = Paths.get(System.getProperty("user.dir"), "Log");
            if (!Files.isDirectory(pathLog)) {
                pathLog.toFile().mkdirs();
            }

            acbrReinf.configGravarValor(ACBrSessao.Principal, "LogNivel", 4);
            acbrReinf.configGravarValor(ACBrSessao.Principal, "LogPath", pathLog.toString());
            acbrReinf.configGravar();

            loadConfig();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated
 
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        saveConfig();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCarregarConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarConfiguracoesActionPerformed
        loadConfig();
    }//GEN-LAST:event_btnCarregarConfiguracoesActionPerformed

    private void btnSelectLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectLogActionPerformed

        try{
            JFileChooser chooser = new JFileChooser(); 
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Selecione o diretorio");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);           
     
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;            
            txtLogs.setText(chooser.getSelectedFile().toString());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "PathSalvar", txtLogs.getText()); 
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectLogActionPerformed

    private void btnSelectSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSchemaActionPerformed

       try{
            JFileChooser chooser = new JFileChooser(); 
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Selecione o diretorio");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);           
     
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;            
            txtSchemaPath.setText(chooser.getSelectedFile().toString());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "PathSchemas", txtSchemaPath.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }       
        
    }//GEN-LAST:event_btnSelectSchemaActionPerformed

    private void btnArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArqActionPerformed

        try{
            JFileChooser chooser = new JFileChooser(); 
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Selecione o diretorio");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);           
     
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;            
            txtArq.setText(chooser.getSelectedFile().toString());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "PathReinf", txtArq.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnArqActionPerformed

    private void btnSelecionarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarCertificadoActionPerformed

       try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("pfx", "Certificado Digital (*.pfx)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            txtCertPath.setText(chooser.getSelectedFile().toString());
            acbrReinf.configGravarValor(ACBrSessao.DFe, "ArquivoPFX", txtCertPath.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelecionarCertificadoActionPerformed

    private void btnCriarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEventoActionPerformed
        try 
        {
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("ini", "Arquivo ini (*.ini)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            acbrReinf.criarEventoReinf(chooser.getSelectedFile().getAbsolutePath());
            rtbRespostas.append("dados carregados."+"\n");
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCriarEventoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try 
        {
             String ret = acbrReinf.enviarReinf();
             rtbRespostas.append(ret+"\n");
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnConsultarProtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProtActionPerformed
        try 
        {
            String eProtocolo = JOptionPane.showInputDialog("Digite o Protocolo");
            
            String ret = acbrReinf.consultarReinf(eProtocolo);
            rtbRespostas.append(ret+"\n");
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarProtActionPerformed

    private void btnCriarEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEnviarActionPerformed
        try 
        {
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("ini", "Arquivo ini (*.ini)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;

            String ret = acbrReinf.criarEnviarReinf(chooser.getSelectedFile().getAbsolutePath());
            rtbRespostas.append(ret+"\n");
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCriarEnviarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        try{
            acbrReinf.limparReinf();
            rtbRespostas.append("Lista Limpa"+"\n"); 
            
        }catch (Exception ex){
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCarregarXMLEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarXMLEventoActionPerformed
        try 
        {
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("xml", "Arquivo xml (*.xml)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            acbrReinf.carregarXMLEventoReinf(chooser.getSelectedFile().getAbsolutePath());
            rtbRespostas.append("xml carregado."+"\n");
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCarregarXMLEventoActionPerformed

    private void btnSetIDContribuinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetIDContribuinteActionPerformed
        try 
        {
            acbrReinf.setIDContribuinte(txtContribuinte.getText());
        } 
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetIDContribuinteActionPerformed

    private void btnSetIDTransmissorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetIDTransmissorActionPerformed
        try 
        {
            acbrReinf.setIDTransmissor(txtTransmissor.getText());
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetIDTransmissorActionPerformed

    private void btnSetTipoContribuinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetTipoContribuinteActionPerformed
        try
        {
            acbrReinf.setTipoContribuinte(cmbTipoContribuinte.getSelectedIndex());
        }
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetTipoContribuinteActionPerformed

    private void btnSetVersaoDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetVersaoDFActionPerformed
        try
        {
            acbrReinf.setVersaoDF(cmbVersaoDF.toString());
        }
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetVersaoDFActionPerformed

    private void btnObterCertificados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObterCertificados1ActionPerformed

        try {
            String ret = acbrReinf.obterCertificados();
            rtbRespostas.append(ret+"\n");
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnObterCertificados1ActionPerformed

    private void btnConsultarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarReciboActionPerformed
        try 
        {
            Date date = Calendar.getInstance().getTime();  
            DateFormat dateFormat = new SimpleDateFormat("YYYY-MM");  
            String strDate = dateFormat.format(date);  
            String ePerApur = JOptionPane.showInputDialog(null, "PerApur", strDate);

            int aTipoEvento = Integer.parseInt(JOptionPane.showInputDialog(null, "TipoEvento", "1000")); 
            String eNrInscEstab = JOptionPane.showInputDialog("NrInscEstab"); 
            String eCnpjPrestador = JOptionPane.showInputDialog("CnpjPrestador");
            String eNrInscTomador = JOptionPane.showInputDialog("NrInscTomador");
            String eDtApur = JOptionPane.showInputDialog("DtApur");
            String eCpfCnpjBenef = JOptionPane.showInputDialog("CpfCnpjBenef");
            String eCnpjFonte = JOptionPane.showInputDialog("CnpjFonte");
            
            String ret = acbrReinf.consultarReciboReinf(ePerApur, aTipoEvento, eNrInscEstab, 
                    eCnpjPrestador, eNrInscTomador, eDtApur, 
                    eCpfCnpjBenef, eCnpjFonte);
            rtbRespostas.append(ret+"\n");
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarReciboActionPerformed

    private void loadConfig() {
        try {
            
            acbrReinf.configLer();
            
            //Config Geral
            ckbExibirErroSchema.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "ExibirErroSchema").equals("1"));
            txtFormatoAlerta.setText(acbrReinf.configLerValor(ACBrSessao.Reinf, "FormatoAlerta"));
            cmbFormaEmissao.setSelectedIndex(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.Reinf, "FormaEmissao")));  
            ckbRetirarAcentos.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "RetirarAcentos").equals("1"));
            ckbSalvar.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "SalvarWS").equals("1"));
            txtLogs.setText(acbrReinf.configLerValor(ACBrSessao.Reinf, "PathSalvar"));
            txtSchemaPath.setText(acbrReinf.configLerValor(ACBrSessao.Reinf, "PathSchemas"));
            txtContribuinte.setText(acbrReinf.configLerValor(ACBrSessao.Reinf, "IdContribuinte"));
            txtTransmissor.setText(acbrReinf.configLerValor(ACBrSessao.Reinf, "IdTransmissor"));
            cmbTipoContribuinte.setSelectedIndex(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.Reinf, "TipoContribuinte")));
            cmbVersaoDF.setSelectedIndex(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.Reinf, "VersaoDF")));
            
            //Config WebService
            cmbUfDestino.setSelectedItem(acbrReinf.configLerValor(ACBrSessao.DFe, "UF"));
            cmbSSlType.setSelectedIndex(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.Reinf, "SSLType")));
            nudTimeOut.setValue(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.Reinf, "Timeout")));
            
            String ambiente = acbrReinf.configLerValor(ACBrSessao.Reinf, "Ambiente");            
            rdbHomologacao.setSelected("1".equals(ambiente));
            rdbProducao.setSelected("0".equals(ambiente));            
            
            ckbVisualizar.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "Visualizar").equals("1"));
            ckbSalvarSOAP.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "SalvarWS").equals("1"));
            ckbAjustarAut.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "AjustaAguardaConsultaRet").equals("1"));
            nudAguardar.setValue(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.Reinf, "AguardarConsultaRet")));
            nudTentativas.setValue(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.Reinf, "Tentativas")));
            nudIntervalos.setValue(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.Reinf, "IntervaloTentativas")));
            
            txtProxyServidor.setText(acbrReinf.configLerValor(ACBrSessao.Proxy, "Servidor"));
            
            String Value = acbrReinf.configLerValor(ACBrSessao.Proxy, "Porta");        
            if(Value.matches("-?\\d+"))
              nudProxyPorta.setValue(Integer.parseInt(Value));           
            
            txtProxyUsuario.setText(acbrReinf.configLerValor(ACBrSessao.Proxy, "Usuario"));
            txtProxySenha.setText(acbrReinf.configLerValor(ACBrSessao.Proxy, "Senha"));
            
            //Config Certificado
            cmbCrypt.setSelectedIndex(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.DFe, "SSLCryptLib")));            
            cmbHttp.setSelectedIndex(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.DFe, "SSLHttpLib")));    
            cmbXmlSign.setSelectedIndex(Integer.parseInt(acbrReinf.configLerValor(ACBrSessao.DFe, "SSLXmlSignLib")));
            txtCertPath.setText(acbrReinf.configLerValor(ACBrSessao.DFe, "ArquivoPFX"));
            txtCertPassword.setText(acbrReinf.configLerValor(ACBrSessao.DFe, "Senha"));
            txtCertNumero.setText(acbrReinf.configLerValor(ACBrSessao.DFe, "NumeroSerie"));
            txtDadosPFX.setText(acbrReinf.configLerValor(ACBrSessao.DFe, "DadosPFX"));
            
            //Config Arquivos
            ckbSalvarArqs.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "SalvarGer").equals("1"));
            ckbPastaMensal.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "SepararPorMes").equals("1"));
            ckbAdicionaLiteral.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "AdicionarLiteral").equals("1"));
            ckbSalvaPathEvento.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "SalvarArq").equals("1"));            
            ckbSepararPorCNPJ.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "SepararPorCNPJ").equals("1"));
            ckbSepararPorModelo.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "SepararPorModelo").equals("1"));
            ckbEmissaoPath.setSelected(acbrReinf.configLerValor(ACBrSessao.Reinf, "EmissaoPathReinf").equals("1"));
            txtArq.setText(acbrReinf.configLerValor(ACBrSessao.Reinf, "PathReinf"));
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveConfig() {
        try {
            
            //Config Geral
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "ExibirErroSchema", ckbExibirErroSchema.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "FormatoAlerta", txtFormatoAlerta.getText());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "FormaEmissao", cmbFormaEmissao.getSelectedIndex());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "RetirarAcentos", ckbRetirarAcentos.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "SalvarWS", ckbSalvar.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "PathSalvar", txtLogs.getText());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "PathSchemas", txtSchemaPath.getText());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "IdContribuinte", txtContribuinte.getText());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "IdTransmissor", txtTransmissor.getText());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "TipoContribuinte", cmbTipoContribuinte.getSelectedIndex());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "VersaoDF", cmbVersaoDF.getSelectedIndex());
                        
            // Config WebService
            acbrReinf.configGravarValor(ACBrSessao.DFe, "UF", cmbUfDestino.getSelectedItem().toString());
            
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "SSLType", cmbSSlType.getSelectedIndex());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "Timeout", nudTimeOut.getValue().toString());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "Ambiente", rdbHomologacao.isSelected() ? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "Visualizar", ckbVisualizar.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "SalvarWS", ckbSalvarSOAP.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "AjustaAguardaConsultaRet", ckbAjustarAut.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "AguardarConsultaRet", nudAguardar.getValue().toString());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "Tentativas", nudTentativas.getValue().toString());
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "IntervaloTentativas", nudIntervalos.getValue().toString());
            
            acbrReinf.configGravarValor(ACBrSessao.Proxy, "Servidor", txtProxyServidor.getText());
            acbrReinf.configGravarValor(ACBrSessao.Proxy, "Porta", nudProxyPorta.getValue().toString());
            acbrReinf.configGravarValor(ACBrSessao.Proxy, "Usuario", txtProxyUsuario.getText());
            acbrReinf.configGravarValor(ACBrSessao.Proxy, "Senha", txtProxySenha.getText());
            
            //Config Certificado
            acbrReinf.configGravarValor(ACBrSessao.DFe, "SSLCryptLib", cmbCrypt.getSelectedIndex());            
            acbrReinf.configGravarValor(ACBrSessao.DFe, "SSLHttpLib", cmbHttp.getSelectedIndex());           
            acbrReinf.configGravarValor(ACBrSessao.DFe, "SSLXmlSignLib", cmbXmlSign.getSelectedIndex());            
            acbrReinf.configGravarValor(ACBrSessao.DFe, "ArquivoPFX", txtCertPath.getText());     
            acbrReinf.configGravarValor(ACBrSessao.DFe, "Senha", new String(txtCertPassword.getPassword()));
            acbrReinf.configGravarValor(ACBrSessao.DFe, "NumeroSerie", txtCertNumero.getText());
            acbrReinf.configGravarValor(ACBrSessao.DFe, "DadosPFX", txtDadosPFX.getText());            
            
            //Config Arquivos
           
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "SalvarGer", ckbSalvarArqs.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "SepararPorMes",ckbPastaMensal.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "AdicionarLiteral", ckbAdicionaLiteral.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "EmissaoPathReinf", ckbEmissaoPath.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "SalvarArq", ckbSalvaPathEvento.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "SepararPorCNPJ", ckbSepararPorCNPJ.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "SepararPorModelo", ckbSepararPorModelo.isSelected()? "1" : "0");
            acbrReinf.configGravarValor(ACBrSessao.Reinf, "PathReinf", txtArq.getText());
            
            acbrReinf.configGravar();            
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArq;
    private javax.swing.JButton btnCarregarConfiguracoes;
    private javax.swing.JButton btnCarregarXMLEvento;
    private javax.swing.JButton btnConsultarProt;
    private javax.swing.JButton btnConsultarRecibo;
    private javax.swing.JButton btnCriarEnviar;
    private javax.swing.JButton btnCriarEvento;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnObterCertificados1;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionarCertificado;
    private javax.swing.JButton btnSelectLog;
    private javax.swing.JButton btnSelectSchema;
    private javax.swing.JButton btnSetIDContribuinte;
    private javax.swing.JButton btnSetIDTransmissor;
    private javax.swing.JButton btnSetTipoContribuinte;
    private javax.swing.JButton btnSetVersaoDF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox ckbAdicionaLiteral;
    private javax.swing.JCheckBox ckbAjustarAut;
    private javax.swing.JCheckBox ckbAttXML;
    private javax.swing.JPanel ckbAtualizarXML;
    private javax.swing.JCheckBox ckbEmissaoPath;
    private javax.swing.JCheckBox ckbExibirErroSchema;
    private javax.swing.JCheckBox ckbPastaMensal;
    private javax.swing.JCheckBox ckbRetirarAcentos;
    private javax.swing.JCheckBox ckbSalvaPathEvento;
    private javax.swing.JCheckBox ckbSalvar;
    private javax.swing.JCheckBox ckbSalvarArqs;
    private javax.swing.JCheckBox ckbSalvarSOAP;
    private javax.swing.JCheckBox ckbSepararPorCNPJ;
    private javax.swing.JCheckBox ckbSepararPorModelo;
    private javax.swing.JCheckBox ckbVisualizar;
    private javax.swing.JComboBox<String> cmbCrypt;
    private javax.swing.JComboBox<String> cmbFormaEmissao;
    private javax.swing.JComboBox<String> cmbHttp;
    private javax.swing.JComboBox<String> cmbSSlType;
    private javax.swing.JComboBox<String> cmbTipoContribuinte;
    private javax.swing.JComboBox<String> cmbUfDestino;
    private javax.swing.JComboBox<String> cmbVersaoDF;
    private javax.swing.JComboBox<String> cmbXmlSign;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JSpinner nudAguardar;
    private javax.swing.JSpinner nudIntervalos;
    private javax.swing.JSpinner nudProxyPorta;
    private javax.swing.JSpinner nudTentativas;
    private javax.swing.JSpinner nudTimeOut;
    private javax.swing.JRadioButton rdbHomologacao;
    private javax.swing.JRadioButton rdbProducao;
    private javax.swing.JTextArea rtbRespostas;
    private javax.swing.JTextField txtArq;
    private javax.swing.JTextField txtCertNumero;
    private javax.swing.JPasswordField txtCertPassword;
    private javax.swing.JTextField txtCertPath;
    private javax.swing.JTextField txtContribuinte;
    private javax.swing.JTextField txtDadosPFX;
    private javax.swing.JTextField txtFormatoAlerta;
    private javax.swing.JTextField txtLogs;
    private javax.swing.JTextField txtProxySenha;
    private javax.swing.JTextField txtProxyServidor;
    private javax.swing.JTextField txtProxyUsuario;
    private javax.swing.JTextField txtSchemaPath;
    private javax.swing.JTextField txtTransmissor;
    // End of variables declaration//GEN-END:variables
}
