namespace ACBrLib.Core.BAL
{
    public enum ACBrBALModelo
    {
        balNenhum,
        balFilizola,
        balToledo,
        balToledo2090,
        balToledo2180,
        balUrano,
        balLucasTec,
        balMagna,
        balDigitron,
        balMagellan,
        balUranoPOP,
        balLider,
        balRinnert,
        balMuller,
        balSaturno,
        balAFTS,
        balGenerica,
        balLibratek,
        balMicheletti,
        balAlfa,
        balToledo9091_8530_8540,
        balWeightechWT1000,
        balMarelCG62XL,
        balWeightechWT3000_ABS,
        balToledo2090N,
        balToledoBCS21,
        balPrecision,
        balDigitron_UL
    }
}