package com.acbr;

public enum  ACBrSessao {
    Principal,
    Versao,
    Sistema,
    Proxy,
    Email,
    SoftwareHouse,
    Emissor,
    PosPrinter,
    PosPrinter_Barras,
    PosPrinter_QRCode,
    PosPrinter_Logo,
    PosPrinter_Gaveta,
    PosPrinter_MPagina,
    ETQ,
    BAL,
    BAL_Device,
    SAT,
    SATConfig,
    SATConfigArquivos,
    SATRede,
    Extrato,
    DFe,
    NFe,
    DANFE,
    DANFECe,
    BoletoConfig,
    BoletoCedenteConfig,
    BoletoBancoConfig,
    BoletoDiretorioConfig,
    BoletoBancoFCFortesConfig,
}
