/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acbr.demo;

//MT

import com.acbr.ACBrSessao;
import com.acbr.NivelLog;
import com.acbr.abecspinpad.*;
import java.awt.Image;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author rften
 */
public class FrmMain extends javax.swing.JFrame {

    private ACBrAbecsPinpad abecsPinpad;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    private void toogleActive() throws Exception {
        if ("Ativar".equals(btnAtivar.getText())) {
            abecsPinpad.ativar();
            btnAtivar.setText("Desativar");
        } else {
            abecsPinpad.desativar();
            btnAtivar.setText("Ativar");
        }
    }

    private void loadConfig(){
        try
        {
            abecsPinpad.configLer();
            
            cmbPortaPinpad.setSelectedIndex(Integer.parseInt(abecsPinpad.configLerValor(ACBrSessao.AbecsPinpad, "PortaPinpad")));
            nudTimeOutPinpad.setValue(Integer.parseInt(abecsPinpad.configLerValor(ACBrSessao.AbecsPinpad, "TimeOut")));
            txtArqLogPinpad.setText(abecsPinpad.configLerValor(ACBrSessao.AbecsPinpad, "LogFile"));
            cmbMsgAlign.setSelectedIndex(Integer.parseInt(abecsPinpad.configLerValor(ACBrSessao.AbecsPinpad, "MsgAlign")));
            ckbWordWrap.setSelected(abecsPinpad.configLerValor(ACBrSessao.AbecsPinpad, "MsgWordWrap").equals("1"));
        }
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }

    private void saveConfig() {
        try 
        {
            abecsPinpad.configGravarValor(ACBrSessao.AbecsPinpad, "PortaPinpad", cmbPortaPinpad.getSelectedIndex());
            abecsPinpad.configGravarValor(ACBrSessao.AbecsPinpad, "TimeOut", nudTimeOutPinpad.getValue().toString());
            abecsPinpad.configGravarValor(ACBrSessao.AbecsPinpad, "LogFile", txtArqLogPinpad.getText());
            abecsPinpad.configGravarValor(ACBrSessao.AbecsPinpad, "MsgAlign", cmbMsgAlign.getSelectedIndex());
            abecsPinpad.configGravarValor(ACBrSessao.AbecsPinpad, "MsgWordWrap", ckbWordWrap.isSelected()? "1" : "0");
            
            abecsPinpad.configGravar();
        }
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbPortaPinpad = new javax.swing.JComboBox<>();
        btnAtivar = new javax.swing.JButton();
        txtArqLogPinpad = new javax.swing.JTextField();
        btnArqLog = new javax.swing.JButton();
        nudTimeOutPinpad = new javax.swing.JSpinner();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        cmbMsgAlign = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        btnSalvarConfiguracoes = new javax.swing.JButton();
        btnCarregarConfiguracoes = new javax.swing.JButton();
        ckbWordWrap = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnGIX = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtbListComandoGIX = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        rtbRespostaGIX = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        btnPinPadCapabilities = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        rtbRespostaPinPadCapabilities = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        btnGIN = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        nudACQIDX = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        rtbRespostaGIN = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnDEX = new javax.swing.JButton();
        btnClearDEX = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        rtbDEXMensagem = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        btnDSP = new javax.swing.JButton();
        btnClearDSP = new javax.swing.JButton();
        txtLinha1 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txtLinha2 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btnLMF = new javax.swing.JButton();
        btnDSI = new javax.swing.JButton();
        btnDMF = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        rtbRespostaLMF = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        rtbRespostaLoadMedia = new javax.swing.JTextArea();
        btnLoadMedia = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        cmbTipoImagem = new javax.swing.JComboBox<>();
        btnCarregarImagem = new javax.swing.JButton();
        txtPathImagem = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        btnGKY = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        btnRMC = new javax.swing.JButton();
        txtRMCLinha1 = new javax.swing.JTextField();
        txtRMCLinha2 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        btnMNU = new javax.swing.JButton();
        txtTituloMNU = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        rtbOpcoesMenu = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        rtbRespostaMNU = new javax.swing.JTextArea();
        nudTimeOutMNU = new javax.swing.JSpinner();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        btnCEX = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        rtbRespostaCEX = new javax.swing.JTextArea();
        nudTimeOutCEX = new javax.swing.JSpinner();
        jLabel62 = new javax.swing.JLabel();
        ckbVerifyKey = new javax.swing.JCheckBox();
        ckbVerifyMagnetic = new javax.swing.JCheckBox();
        ckbVerifyICCInsertion = new javax.swing.JCheckBox();
        ckbVerifyICCRemoval = new javax.swing.JCheckBox();
        ckbVerifyCTLSPresence = new javax.swing.JCheckBox();
        jPanel20 = new javax.swing.JPanel();
        btnGCD = new javax.swing.JButton();
        cmbMsgIndex = new javax.swing.JComboBox<>();
        jLabel57 = new javax.swing.JLabel();
        nudTimeoutGCD = new javax.swing.JSpinner();
        jLabel58 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        rtbRespostaGCD = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        btnCLO = new javax.swing.JButton();
        txtCLOLinha1 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        txtCLOLinha2 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        btnCLXMensagem = new javax.swing.JButton();
        btnCLXImagem = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        rtbCLXMensagem = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnOPN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACBrLibAbecsPinpad");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));

        cmbPortaPinpad.setEditable(true);
        cmbPortaPinpad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "COM10" }));
        cmbPortaPinpad.setToolTipText("");

        btnAtivar.setText("Ativar");
        btnAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtivarActionPerformed(evt);
            }
        });

        txtArqLogPinpad.setToolTipText("");

        btnArqLog.setText("...");
        btnArqLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArqLogActionPerformed(evt);
            }
        });

        nudTimeOutPinpad.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));
        nudTimeOutPinpad.setOpaque(true);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel50.setText("Timeout");

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel51.setText("PortaCOM Pinpad");

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel52.setText("Arq Log Pinpad");

        cmbMsgAlign.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "alNone", "alLeft", "alRight", "alCenter" }));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setText("Msg Align");

        btnSalvarConfiguracoes.setText("Salvar Configurações");
        btnSalvarConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarConfiguracoesActionPerformed(evt);
            }
        });

        btnCarregarConfiguracoes.setLabel("Carregar Configurações");
        btnCarregarConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarConfiguracoesActionPerformed(evt);
            }
        });

        ckbWordWrap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbWordWrap.setText("WordWrap");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtArqLogPinpad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnArqLog, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckbWordWrap)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbMsgAlign, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addContainerGap(96, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel51)
                                    .addComponent(jLabel50)
                                    .addComponent(cmbPortaPinpad, 0, 172, Short.MAX_VALUE)
                                    .addComponent(nudTimeOutPinpad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtivar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCarregarConfiguracoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvarConfiguracoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPortaPinpad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nudTimeOutPinpad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtivar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArqLogPinpad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnArqLog)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMsgAlign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbWordWrap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarConfiguracoes)
                    .addComponent(btnCarregarConfiguracoes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("GIX"));

        btnGIX.setText("GIX");
        btnGIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGIXActionPerformed(evt);
            }
        });

        rtbListComandoGIX.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "PP_SERNUM", "PP_PARTNBR", "PP_MODEL", "PP_MNNAME", "PP_CAPAB", "PP_SOVER", "PP_SPECVER", "PP_MANVERS", "PP_APPVERS", "PP_GENVERS", "PP_KRNLVER", "PP_CTLSVER", "PP_MCTLSVER", "PP_VCTLSVER", "PP_AECTLSVER", "PP_DPCTLSVER", "PP_PUREVER", "PP_DSPTXTSZ", "PP_DSPGRSZ", "PP_MFSUP", "PP_MKTDESP", "PP_MKTDESD", "PP_DKPTTDESP", "PP_DKPTTDESD", "PP_EVENT", "PP_TRK1INC", "PP_TRK2INC", "PP_TRK3INC", "PP_TRACK1", "PP_TRACK2", "PP_TRACK3", "PP_TRK1KSN", "PP_TRK2KSN", "PP_TRK3KSN", "PP_ENCPAN", "PP_ENCPANKSN", "PP_KSN", "PP_VALUE", "PP_DATAOUT", "PP_CARDTYPE", "PP_ICCSTAT", "PP_AIDTABINFO", "PP_PAN", "PP_PANSEQNO", "PP_EMVDATA", "PP_CHNAME", "PP_GOXRES", "PP_PINBLK", "PP_FCXRES", "PP_ISRESULTS", "PP_BIGRAND", "PP_LABEL", "PP_ISSCNTRY", "PP_CARDEXP", "PP_MFNAME", "PP_DEVTYPE", "PP_TLRMEM", "PP_ENCKRAND", "PP_KSNTDESP00", "PP_KSNTDESP63", "PP_KSNTDESD00", "PP_KSNTDESD63", "PP_TABVER00", "PP_TABVER63" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        rtbListComandoGIX.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rtbListComandoGIX.setToolTipText("");
        jScrollPane1.setViewportView(rtbListComandoGIX);

        rtbRespostaGIX.setColumns(20);
        rtbRespostaGIX.setRows(5);
        jScrollPane2.setViewportView(rtbRespostaGIX);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnGIX, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGIX)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("PinPad Capabilities"));

        btnPinPadCapabilities.setText("PinPadCapabilities");
        btnPinPadCapabilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinPadCapabilitiesActionPerformed(evt);
            }
        });

        rtbRespostaPinPadCapabilities.setColumns(20);
        rtbRespostaPinPadCapabilities.setRows(5);
        jScrollPane3.setViewportView(rtbRespostaPinPadCapabilities);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnPinPadCapabilities, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(73, 73, 73))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPinPadCapabilities)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("GIN"));

        btnGIN.setText("GIN");
        btnGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGINActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setText("GIN_ACQIDX");

        rtbRespostaGIN.setColumns(20);
        rtbRespostaGIN.setRows(5);
        jScrollPane4.setViewportView(rtbRespostaGIN);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nudACQIDX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGIN)
                    .addComponent(jLabel53)
                    .addComponent(nudACQIDX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Informações", jPanel3);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("DEX"));

        btnDEX.setText("Display (DEX)");
        btnDEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDEXActionPerformed(evt);
            }
        });

        btnClearDEX.setText("Clear DEX");
        btnClearDEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearDEXActionPerformed(evt);
            }
        });

        rtbDEXMensagem.setColumns(20);
        rtbDEXMensagem.setRows(5);
        rtbDEXMensagem.setText("PROJETO ACBR\nACBrAbecsPinPad\n----------------\nTEF e PIX ? É no ACBr\n-+-+-+-+-+-+-+-+");
        jScrollPane5.setViewportView(rtbDEXMensagem);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDEX, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnClearDEX, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearDEX)
                    .addComponent(btnDEX))
                .addGap(16, 16, 16))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("DSP"));

        btnDSP.setText("Display (DSP)");
        btnDSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSPActionPerformed(evt);
            }
        });

        btnClearDSP.setText("Clear DSP");
        btnClearDSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearDSPActionPerformed(evt);
            }
        });

        txtLinha1.setText("PROJETO ACBR");
        txtLinha1.setToolTipText("");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setText("Linha 1");

        txtLinha2.setText("ACBrAbecsPinpad");
        txtLinha2.setToolTipText("");

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel55.setText("Linha 2");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel55)
                    .addComponent(txtLinha2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(btnDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtLinha1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLinha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLinha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDSP)
                    .addComponent(btnClearDSP))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Display", jPanel4);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Media Files"));

        btnLMF.setText("List (LMF)");
        btnLMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLMFActionPerformed(evt);
            }
        });

        btnDSI.setText("Display (DSI)");
        btnDSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSIActionPerformed(evt);
            }
        });

        btnDMF.setText("Delete (DMF)");
        btnDMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMFActionPerformed(evt);
            }
        });

        rtbRespostaLMF.setColumns(20);
        rtbRespostaLMF.setRows(5);
        jScrollPane7.setViewportView(rtbRespostaLMF);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btnLMF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDSI, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDMF, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLMF)
                    .addComponent(btnDSI)
                    .addComponent(btnDMF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7)
                .addContainerGap())
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem"));

        rtbRespostaLoadMedia.setColumns(20);
        rtbRespostaLoadMedia.setRows(5);
        jScrollPane6.setViewportView(rtbRespostaLoadMedia);

        btnLoadMedia.setText("LoadMedia");
        btnLoadMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadMediaActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setText("Tipo Imagem");

        cmbTipoImagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PNG", "JPG", "GIF" }));

        btnCarregarImagem.setText("...");
        btnCarregarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarImagemActionPerformed(evt);
            }
        });

        txtPathImagem.setToolTipText("");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setText("Path Imagem");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel56)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(cmbTipoImagem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLoadMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPathImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarregarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPathImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarImagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addGap(8, 8, 8)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Multimidia", jPanel8);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("GKY"));

        btnGKY.setText("GKY");
        btnGKY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGKYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnGKY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(91, 91, 91))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnGKY)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("RMC"));

        btnRMC.setText("RMC");
        btnRMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRMCActionPerformed(evt);
            }
        });

        txtRMCLinha1.setText("OPERATION");
        txtRMCLinha1.setToolTipText("");

        txtRMCLinha2.setText("FINISHED");
        txtRMCLinha2.setToolTipText("");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRMCLinha2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRMCLinha1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnRMC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtRMCLinha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRMCLinha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRMC)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("MNU"));

        btnMNU.setText("MNU");
        btnMNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMNUActionPerformed(evt);
            }
        });

        txtTituloMNU.setToolTipText("");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel59.setText("Titulo Menu");

        rtbOpcoesMenu.setColumns(20);
        rtbOpcoesMenu.setRows(5);
        jScrollPane9.setViewportView(rtbOpcoesMenu);

        rtbRespostaMNU.setColumns(20);
        rtbRespostaMNU.setRows(5);
        jScrollPane10.setViewportView(rtbRespostaMNU);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setText("TimeOut");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setText("Opções");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nudTimeOutMNU)
                            .addComponent(btnMNU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTituloMNU)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTituloMNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(jLabel61))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(nudTimeOutMNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMNU))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("CEX"));

        btnCEX.setText("CEX");
        btnCEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEXActionPerformed(evt);
            }
        });

        rtbRespostaCEX.setColumns(20);
        rtbRespostaCEX.setRows(5);
        jScrollPane11.setViewportView(rtbRespostaCEX);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel62.setText("TimeOut");

        ckbVerifyKey.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbVerifyKey.setText("Verify Key");

        ckbVerifyMagnetic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbVerifyMagnetic.setText("Verify Magnetic");

        ckbVerifyICCInsertion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbVerifyICCInsertion.setText("Verify ICC Insertion");

        ckbVerifyICCRemoval.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbVerifyICCRemoval.setText("Verify ICC Removal");

        ckbVerifyCTLSPresence.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbVerifyCTLSPresence.setText("Verify CTLS Presence");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCEX)
                .addGap(92, 92, 92))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(ckbVerifyKey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel62)
                            .addComponent(nudTimeOutCEX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbVerifyCTLSPresence)
                            .addComponent(ckbVerifyICCRemoval)
                            .addComponent(ckbVerifyICCInsertion)
                            .addComponent(ckbVerifyMagnetic))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nudTimeOutCEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbVerifyKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbVerifyMagnetic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbVerifyICCInsertion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbVerifyICCRemoval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ckbVerifyCTLSPresence)
                .addGap(18, 18, 18)
                .addComponent(btnCEX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("GCD"));

        btnGCD.setText("GCD");
        btnGCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGCDActionPerformed(evt);
            }
        });

        cmbMsgIndex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DigiteDDD", "RedigiteDDD", "DigiteTelefone", "RedigiteTelefone", "DigiteDDDeTelefone", "RedigiteDDDeTelefone", "DigiteCPF", "RedigiteCPF", "DigiteRG", "RedigiteRG", "Digite4UltimosDigitos", "DigiteCodSeguranca", "DigiteCNPJ", "RedigiteCNPJ", "DigiteDataDDMMAAAA", "DigiteDataDDMMAA", "DigiteDataDDMM", "DigiteDiaDD", "DigiteMesMM", "DigiteAnoAA", "DigiteAnoAAAA", "DataNascimentoDDMMAAAA", "DataNascimentoDDMMAA", "DataNascimentoDDMM", "DiaNascimentoDD", "MesNascimentoMM", "AnoNascimentoAA", "AnoNascimentoAAAA", "DigiteIdentificacao", "CodFidelidade", "NumeroMesa", "QtdPessoas", "Quantidade", "NumeroBomba", "NumeroVaga", "NumeroGuiche", "CodVendedor", "CodGarcom", "NotaAtendimento", "NumeroNotaFiscal", "NumeroComanda", "PlacaVeiculo", "DigiteQuilometragem", "QuilometragemInicial", "QuilometragemFinal", "DigitePorcentagem", "PesquisaSatisfacao0_10", "AvalieAtendimento0_10", "DigiteToken", "DigiteNumeroCartao", "NumeroParcelas", "CodigoPlano", "CodigoProduto" }));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel57.setText("Msg Index");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel58.setText("TimeOut");

        rtbRespostaGCD.setColumns(20);
        rtbRespostaGCD.setRows(5);
        jScrollPane8.setViewportView(rtbRespostaGCD);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMsgIndex, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel57)
                                    .addComponent(jLabel58))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addComponent(nudTimeoutGCD, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57)
                .addGap(8, 8, 8)
                .addComponent(cmbMsgIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nudTimeoutGCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGCD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 320, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Perguntas/Eventos", jPanel9);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("CLO"));

        btnCLO.setText("CLO");
        btnCLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLOActionPerformed(evt);
            }
        });

        txtCLOLinha1.setText("Comunicação");
        txtCLOLinha1.setToolTipText("");

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel63.setText("Linha 1");

        txtCLOLinha2.setText("Finalizada");
        txtCLOLinha2.setToolTipText("");

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel64.setText("Linha 2");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64)
                    .addComponent(txtCLOLinha2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63)
                    .addComponent(txtCLOLinha1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnCLO, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCLOLinha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCLOLinha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCLO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("CLX"));

        btnCLXMensagem.setText("CLX Mensagem");
        btnCLXMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLXMensagemActionPerformed(evt);
            }
        });

        btnCLXImagem.setText("CLX Imagem");
        btnCLXImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLXImagemActionPerformed(evt);
            }
        });

        rtbCLXMensagem.setColumns(20);
        rtbCLXMensagem.setRows(5);
        rtbCLXMensagem.setText("PROJETO ACBR\nACBrAbecsPinPad\n----------------\nTEF e PIX ? É no ACBr\n-+-+-+-+-+-+-+-+");
        jScrollPane12.setViewportView(rtbCLXMensagem);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCLXMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnCLXImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCLXImagem)
                    .addComponent(btnCLXMensagem))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Finalizar Comunicação", jPanel10);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Abrir Comunicação"));

        btnOPN.setText("OPN");
        btnOPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOPNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(btnOPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(87, 87, 87)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(btnOPN)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArqLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArqLogActionPerformed
        JFileChooser chooser = new JFileChooser();
        OpenFileFilter filter = new OpenFileFilter("log", "Log File (*.log)");
        chooser.addChoosableFileFilter(filter);
        chooser.setFileFilter(filter);

        int returnVal = chooser.showSaveDialog(rootPane);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            txtArqLogPinpad.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnArqLogActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            abecsPinpad = new ACBrAbecsPinpad();

            loadConfig();

            Path path = Paths.get(System.getProperty("user.dir"), "Logs");
            if (!Files.isDirectory(path)) {
                path.toFile().mkdirs();
            }

            abecsPinpad.configGravarValor(ACBrSessao.Principal, "LogNivel", NivelLog.logParanoico);
            abecsPinpad.configGravarValor(ACBrSessao.Principal, "LogPath", path);
            abecsPinpad.configGravar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarActionPerformed
        try {
            toogleActive();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnAtivarActionPerformed

    private void btnSalvarConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarConfiguracoesActionPerformed
        saveConfig();
    }//GEN-LAST:event_btnSalvarConfiguracoesActionPerformed

    private void btnCarregarConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarConfiguracoesActionPerformed
        loadConfig();
    }//GEN-LAST:event_btnCarregarConfiguracoesActionPerformed

    private void btnOPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOPNActionPerformed
        try {
            abecsPinpad.OPN();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnOPNActionPerformed

    private void btnGIXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGIXActionPerformed
        try {
            String PPDATA = JOptionPane.showInputDialog("Informe PPDATA:");
            String ret = abecsPinpad.GIX(PPDATA);
            rtbRespostaGIX.append(ret);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnGIXActionPerformed

    private void btnPinPadCapabilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinPadCapabilitiesActionPerformed
        try {
            String ret = abecsPinpad.PinPadCapabilities();
            rtbRespostaPinPadCapabilities.append(ret);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnPinPadCapabilitiesActionPerformed

    private void btnGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGINActionPerformed
        try {
            int ACQIDX = (int)nudACQIDX.getValue();
            String ret = abecsPinpad.GIN(ACQIDX);
            rtbRespostaGIN.append(ret);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnGINActionPerformed

    private void btnDSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSPActionPerformed
        try {
            String msg = txtLinha1.getText() +"\n"+ txtLinha2.getText();
            abecsPinpad.DSP(msg);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnDSPActionPerformed

    private void btnClearDSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDSPActionPerformed
        try {
            abecsPinpad.DSP("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnClearDSPActionPerformed

    private void btnDEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDEXActionPerformed
        try {
            abecsPinpad.DEX(rtbDEXMensagem.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnDEXActionPerformed

    private void btnClearDEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDEXActionPerformed
        try {
            abecsPinpad.DEX("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnClearDEXActionPerformed

    private void btnLMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLMFActionPerformed
        try {
            String ret = abecsPinpad.LMF();
            rtbRespostaLMF.append(ret);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnLMFActionPerformed

    private void btnDSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSIActionPerformed
        try {
            String NomeArquivo = JOptionPane.showInputDialog("Informe Nome da Imagem:");
            abecsPinpad.DSI(NomeArquivo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnDSIActionPerformed

    private void btnDMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMFActionPerformed
        try {
            String NomeArquivo = JOptionPane.showInputDialog("Informe Nome da Imagem:");
            abecsPinpad.DMF(NomeArquivo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnDMFActionPerformed

    private void btnGKYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGKYActionPerformed
        try {
            abecsPinpad.GKY();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnGKYActionPerformed

    private void btnRMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRMCActionPerformed
        try {
            String msg = txtRMCLinha1.getText() +"\n"+ txtRMCLinha2.getText();
            abecsPinpad.RMC(msg);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnRMCActionPerformed

    private void btnMNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMNUActionPerformed
        try {
            int TimeOutMNU = (int)nudTimeOutMNU.getValue();
            String ret = abecsPinpad.MNU(rtbOpcoesMenu.getText(), txtTituloMNU.getText(), TimeOutMNU);
            rtbRespostaMNU.append(ret);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnMNUActionPerformed

    private void btnCEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEXActionPerformed
        int TimeOutCEX = (int)nudTimeOutCEX.getValue();
        if (ckbVerifyKey.isSelected()) {
            try {
                abecsPinpad.DEX("Press Key");
                String ret = abecsPinpad.CEX(true, false, false, false, false, TimeOutCEX);
                rtbRespostaCEX.append(ret);
                abecsPinpad.DEX("");
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (ckbVerifyMagnetic.isSelected()) {
            try {
                abecsPinpad.DEX("Swipe the card");
                String ret = abecsPinpad.CEX(false, true, false, false, false, TimeOutCEX);
                rtbRespostaCEX.append(ret);
                abecsPinpad.DEX("");
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (ckbVerifyICCInsertion.isSelected()) {
            try {
                abecsPinpad.DEX("Insert card");
                String ret = abecsPinpad.CEX(false, false, true, false, false, TimeOutCEX);
                rtbRespostaCEX.append(ret);
                abecsPinpad.DEX("");
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (ckbVerifyICCRemoval.isSelected()){
            try {
                abecsPinpad.DEX("Remove card");
                String ret = abecsPinpad.CEX(false, false, false, true, false, TimeOutCEX);
                rtbRespostaCEX.append(ret);
                abecsPinpad.DEX("");
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (ckbVerifyCTLSPresence.isSelected()){
            try {
                abecsPinpad.DEX("Bring card closer");
                String ret = abecsPinpad.CEX(false, false, false, false, true, TimeOutCEX);
                rtbRespostaCEX.append(ret);
                abecsPinpad.DEX("");
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCEXActionPerformed

    private void btnGCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGCDActionPerformed
        try {
            int TimeOutGDC = (int)nudTimeoutGCD.getValue();
            String ret = abecsPinpad.GCD(cmbMsgIndex.getSelectedIndex(), TimeOutGDC);
            rtbRespostaGCD.append(ret);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnGCDActionPerformed

    private void btnCLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLOActionPerformed
        try {
            String msg = txtCLOLinha1.getText() +"\n"+ txtCLOLinha2.getText();
            abecsPinpad.CLO(msg);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnCLOActionPerformed

    private void btnCLXMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLXMensagemActionPerformed
        try {
            abecsPinpad.CLX(rtbCLXMensagem.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnCLXMensagemActionPerformed

    private void btnCLXImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLXImagemActionPerformed
        try {
            String NomeArquivo = JOptionPane.showInputDialog("Informe Nome da Imagem:");
            abecsPinpad.CLX(NomeArquivo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnCLXImagemActionPerformed

    private void btnCarregarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarImagemActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("*.png; *.jpg; *.gif", "Image files (*.png, *.jpg, *.gif)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);

            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            txtPathImagem.setText(chooser.getSelectedFile().toString());
                        
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCarregarImagemActionPerformed

    private void btnLoadMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadMediaActionPerformed
        try {
            String ret = abecsPinpad.LoadMedia(txtPathImagem.getText(), cmbTipoImagem.getSelectedIndex());
            rtbRespostaLoadMedia.append(ret);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnLoadMediaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArqLog;
    private javax.swing.JButton btnAtivar;
    private javax.swing.JButton btnCEX;
    private javax.swing.JButton btnCLO;
    private javax.swing.JButton btnCLXImagem;
    private javax.swing.JButton btnCLXMensagem;
    private javax.swing.JButton btnCarregarConfiguracoes;
    private javax.swing.JButton btnCarregarImagem;
    private javax.swing.JButton btnClearDEX;
    private javax.swing.JButton btnClearDSP;
    private javax.swing.JButton btnDEX;
    private javax.swing.JButton btnDMF;
    private javax.swing.JButton btnDSI;
    private javax.swing.JButton btnDSP;
    private javax.swing.JButton btnGCD;
    private javax.swing.JButton btnGIN;
    private javax.swing.JButton btnGIX;
    private javax.swing.JButton btnGKY;
    private javax.swing.JButton btnLMF;
    private javax.swing.JButton btnLoadMedia;
    private javax.swing.JButton btnMNU;
    private javax.swing.JButton btnOPN;
    private javax.swing.JButton btnPinPadCapabilities;
    private javax.swing.JButton btnRMC;
    private javax.swing.JButton btnSalvarConfiguracoes;
    private javax.swing.JCheckBox ckbVerifyCTLSPresence;
    private javax.swing.JCheckBox ckbVerifyICCInsertion;
    private javax.swing.JCheckBox ckbVerifyICCRemoval;
    private javax.swing.JCheckBox ckbVerifyKey;
    private javax.swing.JCheckBox ckbVerifyMagnetic;
    private javax.swing.JCheckBox ckbWordWrap;
    private javax.swing.JComboBox<String> cmbMsgAlign;
    private javax.swing.JComboBox<String> cmbMsgIndex;
    private javax.swing.JComboBox<String> cmbPortaPinpad;
    private javax.swing.JComboBox<String> cmbTipoImagem;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner nudACQIDX;
    private javax.swing.JSpinner nudTimeOutCEX;
    private javax.swing.JSpinner nudTimeOutMNU;
    private javax.swing.JSpinner nudTimeOutPinpad;
    private javax.swing.JSpinner nudTimeoutGCD;
    private javax.swing.JTextArea rtbCLXMensagem;
    private javax.swing.JTextArea rtbDEXMensagem;
    private javax.swing.JList<String> rtbListComandoGIX;
    private javax.swing.JTextArea rtbOpcoesMenu;
    private javax.swing.JTextArea rtbRespostaCEX;
    private javax.swing.JTextArea rtbRespostaGCD;
    private javax.swing.JTextArea rtbRespostaGIN;
    private javax.swing.JTextArea rtbRespostaGIX;
    private javax.swing.JTextArea rtbRespostaLMF;
    private javax.swing.JTextArea rtbRespostaLoadMedia;
    private javax.swing.JTextArea rtbRespostaMNU;
    private javax.swing.JTextArea rtbRespostaPinPadCapabilities;
    private javax.swing.JTextField txtArqLogPinpad;
    private javax.swing.JTextField txtCLOLinha1;
    private javax.swing.JTextField txtCLOLinha2;
    private javax.swing.JTextField txtLinha1;
    private javax.swing.JTextField txtLinha2;
    private javax.swing.JTextField txtPathImagem;
    private javax.swing.JTextField txtRMCLinha1;
    private javax.swing.JTextField txtRMCLinha2;
    private javax.swing.JTextField txtTituloMNU;
    // End of variables declaration//GEN-END:variables
}
