/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acbr.nfe.demo;

import com.acbr.nfe.ACBrNFe;
import com.sun.jna.ptr.IntByReference;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author rften
 */
public class FrmMain extends javax.swing.JFrame {

    private ACBrNFe acbrNFe;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        try {
            acbrNFe = ACBrNFe.INSTANCE;
            int ret = acbrNFe.NFE_Inicializar(ACBrNFe.toUTF8(Paths.get(System.getProperty("user.dir"), "ACBrLib.ini").toString()), ACBrNFe.toUTF8(""));
            ACBrNFe.checkResult(ret);
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbModeloDocumento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtIdCSC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCSC = new javax.swing.JTextField();
        txtSchemaPath = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSelectSchema = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmbUfDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbSSlType = new javax.swing.JComboBox<>();
        nudTimeOut = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rdbHomologacao = new javax.swing.JRadioButton();
        rdbProducao = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtProxyServidor = new javax.swing.JTextField();
        nudProxyPorta = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtProxyUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtProxySenha = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cmbCrypt = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbHttp = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbXmlSign = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtCertPath = new javax.swing.JTextField();
        btnSelectCert = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCertNumero = new javax.swing.JTextField();
        txtCertPassword = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        nudPorta = new javax.swing.JSpinner();
        txtUsuario = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ckbSSL = new javax.swing.JCheckBox();
        ckbTLS = new javax.swing.JCheckBox();
        txtSenha = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        txtAssunto = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        btnConsultaXml = new javax.swing.JButton();
        btnConsultaChave = new javax.swing.JButton();
        btnConsultarRecibo = new javax.swing.JButton();
        btnCancelarNFe = new javax.swing.JButton();
        btnInutilizar = new javax.swing.JButton();
        btnEnviarEmail = new javax.swing.JButton();
        btnStatusServ = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtbRespostas = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACBrLibNFe Demo");
        setPreferredSize(new java.awt.Dimension(701, 531));
        setSize(new java.awt.Dimension(701, 531));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        cmbModeloDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "moNFe", "moNFCe" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Modelo Documento Fiscal");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("IdCSC");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CSC");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Pasta dos Schemas");

        btnSelectSchema.setText("jButton1");
        btnSelectSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSchemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cmbModeloDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addComponent(txtSchemaPath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectSchema, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIdCSC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCSC))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbModeloDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdCSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSchemaPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectSchema))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configurações", jPanel1);

        cmbUfDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("UF Destino");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("SSL Type");

        cmbSSlType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LT_all", "LT_SSLv2", "LT_SSLv3", "LT_TLSv1", "LT_TLSv1_1", "LT_TLSv1_2", "LT_SSHv2" }));

        nudTimeOut.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("TimeOut");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ambiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        rdbHomologacao.setText("Homologação");

        rdbProducao.setText("Produção");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbHomologacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbProducao)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHomologacao)
                    .addComponent(rdbProducao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proxy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Servidor");

        nudProxyPorta.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Porta");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Usuário");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Senha");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProxyServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13))
                            .addComponent(nudProxyPorta)))
                    .addComponent(txtProxyUsuario)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtProxySenha))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nudProxyPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProxyServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProxyUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProxySenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbUfDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbSSlType, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addGap(50, 50, 50)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addGap(23, 23, 23))
                            .addComponent(nudTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSSlType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nudTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Webservices", jPanel2);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("CryptLib");

        cmbCrypt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cryNone", "cryOpenSSL", "cryCapicom", "cryWinCrypt" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("HttpLib");

        cmbHttp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "httpNone", "httpWinINet", "httpWinHttp", "httpOpenSSL", "httpIndy" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("XmlSignLib");

        cmbXmlSign.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "xsNone", "xsXmlSec", "xsMsXml", "xsMsXmlCapicom", "xsLibXml2" }));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Certificados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Caminho");

        btnSelectCert.setText("jButton1");
        btnSelectCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCertActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Senha");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Número de Série");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtCertPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelectCert, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtCertNumero)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtCertPassword)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCertPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectCert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCertPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCertNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(cmbCrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(cmbHttp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cmbXmlSign, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbHttp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbXmlSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Certificados", jPanel3);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Nome");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Host SMTP");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Email");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Porta");

        nudPorta.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Usuário");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Senha");

        ckbSSL.setText("SSL");

        ckbTLS.setText("TLS");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addComponent(txtEmail)
                    .addComponent(txtHost)
                    .addComponent(txtUsuario)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nudPorta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbSSL)
                            .addComponent(ckbTLS))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtSenha))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(1, 1, 1)
                .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ckbSSL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nudPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbTLS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(1, 1, 1)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Assunto");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Mensagem");

        txtMensagem.setColumns(20);
        txtMensagem.setRows(5);
        jScrollPane2.setViewportView(txtMensagem);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAssunto)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Email", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Comandos"));

        btnConsultaXml.setText("Consultar com Xml");
        btnConsultaXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaXmlActionPerformed(evt);
            }
        });

        btnConsultaChave.setText("Consultar com Chave");
        btnConsultaChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaChaveActionPerformed(evt);
            }
        });

        btnConsultarRecibo.setText("Consultar Recibo");
        btnConsultarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarReciboActionPerformed(evt);
            }
        });

        btnCancelarNFe.setText("Cancelar NFe");
        btnCancelarNFe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNFeActionPerformed(evt);
            }
        });

        btnInutilizar.setText("Inutilizar Numeração");
        btnInutilizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInutilizarActionPerformed(evt);
            }
        });

        btnEnviarEmail.setText("Enviar NFe Email");
        btnEnviarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEmailActionPerformed(evt);
            }
        });

        btnStatusServ.setText(" Status de Serviço");
        btnStatusServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusServActionPerformed(evt);
            }
        });

        btnEnviar.setText("Criar e Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir DANFe");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnConsultaXml, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultaChave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(btnConsultarRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCancelarNFe, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInutilizar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(btnEnviarEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnStatusServ, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStatusServ)
                    .addComponent(btnEnviar)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultaXml)
                    .addComponent(btnConsultaChave)
                    .addComponent(btnConsultarRecibo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarEmail)
                    .addComponent(btnInutilizar)
                    .addComponent(btnCancelarNFe))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Respostas"));

        rtbRespostas.setColumns(20);
        rtbRespostas.setRows(5);
        jScrollPane1.setViewportView(rtbRespostas);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        btnSalvar.setText("Salvar Configurações");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnSalvar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            // Altera as config de log
            Path pathLog = Paths.get(System.getProperty("user.dir"), "Log");
            if (!Files.isDirectory(pathLog)) {
                pathLog.toFile().mkdirs();
            }

            int ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Principal"), ACBrNFe.toUTF8("LogNivel"), "4");
            ACBrNFe.checkResult(ret);

            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Principal"), ACBrNFe.toUTF8("LogPath"), pathLog.toString());
            ACBrNFe.checkResult(ret);

            ret = acbrNFe.NFE_ConfigGravar(ACBrNFe.toUTF8(""));
            ACBrNFe.checkResult(ret);

            loadConfig();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        saveConfig();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnStatusServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusServActionPerformed
        try{
            ByteBuffer buffer = ByteBuffer.allocate(256);
            IntByReference bufferLen = new IntByReference(256);
            
            int ret = acbrNFe.NFE_StatusServico(buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            if (bufferLen.getValue() > 256) {
                buffer = ByteBuffer.allocate(bufferLen.getValue());
                acbrNFe.NFE_UltimoRetorno(buffer, bufferLen);
            }
            
            rtbRespostas.append(ACBrNFe.fromUTF8(buffer, bufferLen));
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStatusServActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("ini", "Arquivo Ini NFe (*.ini)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            int ret = acbrNFe.NFE_LimparLista();
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_CarregarINI(ACBrNFe.toUTF8(chooser.getSelectedFile().getAbsolutePath()));
            ACBrNFe.checkResult(ret);
            
            ByteBuffer buffer = ByteBuffer.allocate(256);
            IntByReference bufferLen = new IntByReference(256);
            
            ret = acbrNFe.NFE_Enviar(1, false, false, false, buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            if (bufferLen.getValue() > 1024)
            {
                ret = acbrNFe.NFE_UltimoRetorno(buffer, bufferLen);
                ACBrNFe.checkResult(ret);
            }
            
            rtbRespostas.append(ACBrNFe.fromUTF8(buffer, bufferLen));            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("xml", "Arquivo Xml NFe (*.xml)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            int ret = acbrNFe.NFE_LimparLista();
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_CarregarXML(ACBrNFe.toUTF8(chooser.getSelectedFile().getAbsolutePath()));
            ACBrNFe.checkResult(ret);
                        
            ret = acbrNFe.NFE_Imprimir("", 1, "", "1", "", "", "");
            ACBrNFe.checkResult(ret);
            
            rtbRespostas.append("Impresso com sucesso.");            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnConsultaXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaXmlActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("xml", "Arquivo Xml NFe (*.xml)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            
            ByteBuffer buffer = ByteBuffer.allocate(256);
            IntByReference bufferLen = new IntByReference(256);
            
            int ret = acbrNFe.NFE_Consultar(ACBrNFe.toUTF8(chooser.getSelectedFile().getAbsolutePath()), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            if (bufferLen.getValue() > 1024)
            {
                ret = acbrNFe.NFE_UltimoRetorno(buffer, bufferLen);
                ACBrNFe.checkResult(ret);
            }
            
            rtbRespostas.append(ACBrNFe.fromUTF8(buffer, bufferLen));
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultaXmlActionPerformed

    private void btnConsultaChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaChaveActionPerformed
        try{
            String chaveOuNFe = JOptionPane.showInputDialog(this, "Chave da NF-e:", 
                    "WebServices Consultar", JOptionPane.PLAIN_MESSAGE);

            ByteBuffer buffer = ByteBuffer.allocate(256);
            IntByReference bufferLen = new IntByReference(256);
            
            int ret = acbrNFe.NFE_Consultar(ACBrNFe.toUTF8(chaveOuNFe), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            if (bufferLen.getValue() > 1024)
            {
                ret = acbrNFe.NFE_UltimoRetorno(buffer, bufferLen);
                ACBrNFe.checkResult(ret);
            }
            
            rtbRespostas.append(ACBrNFe.fromUTF8(buffer, bufferLen));            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultaChaveActionPerformed

    private void btnConsultarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarReciboActionPerformed
        try{
            String recibo = JOptionPane.showInputDialog(this, "Número do recibo:", 
                    "WebServices Consultar", JOptionPane.PLAIN_MESSAGE);

            ByteBuffer buffer = ByteBuffer.allocate(256);
            IntByReference bufferLen = new IntByReference(256);
            
            int ret = acbrNFe.NFE_ConsultarRecibo(ACBrNFe.toUTF8(recibo), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            if (bufferLen.getValue() > 1024)
            {
                ret = acbrNFe.NFE_UltimoRetorno(buffer, bufferLen);
                ACBrNFe.checkResult(ret);
            }
            
            rtbRespostas.append(ACBrNFe.fromUTF8(buffer, bufferLen));                 
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarReciboActionPerformed

    private void btnCancelarNFeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNFeActionPerformed
        try{
            String idLote = JOptionPane.showInputDialog(this, "Identificador de controle do Lote de envio do Evento:", 
                    "WebServices Eventos: Cancelamento", JOptionPane.PLAIN_MESSAGE);
            String eChave = JOptionPane.showInputDialog(this, "Chave da NF-e:", 
                    "WebServices Eventos: Cancelamento", JOptionPane.PLAIN_MESSAGE);
            String eCNPJ = JOptionPane.showInputDialog(this, "CNPJ ou o CPF do autor do Evento:", 
                    "WebServices Eventos: Cancelamento", JOptionPane.PLAIN_MESSAGE);
            String aJustificativa = JOptionPane.showInputDialog(this, "Justificativa do Cancelamento:", 
                    "WebServices Eventos: Cancelamento", JOptionPane.PLAIN_MESSAGE);
            
            ByteBuffer buffer = ByteBuffer.allocate(256);
            IntByReference bufferLen = new IntByReference(256);
            
            int ret = acbrNFe.NFE_Cancelar(ACBrNFe.toUTF8(eChave),
                                           ACBrNFe.toUTF8(aJustificativa),
                                           ACBrNFe.toUTF8(eCNPJ),
                                           Integer.parseInt(idLote),
                                           buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            if (bufferLen.getValue() > 1024)
            {
                ret = acbrNFe.NFE_UltimoRetorno(buffer, bufferLen);
                ACBrNFe.checkResult(ret);
            }
            
            rtbRespostas.append(ACBrNFe.fromUTF8(buffer, bufferLen));
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarNFeActionPerformed

    private void btnInutilizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInutilizarActionPerformed
        try{
            String ano = JOptionPane.showInputDialog(this, "Ano", 
                    "WebServices Inutilização", JOptionPane.PLAIN_MESSAGE);
            String modelo = JOptionPane.showInputDialog(this, "Modelo", 
                    "WebServices Inutilização", JOptionPane.PLAIN_MESSAGE);            
            String serie = JOptionPane.showInputDialog(this, "Serie", 
                    "WebServices Inutilização", JOptionPane.PLAIN_MESSAGE);
            String numeroInicial = JOptionPane.showInputDialog(this, "Número Inicial", 
                    "WebServices Inutilização", JOptionPane.PLAIN_MESSAGE);
            String numeroFinal = JOptionPane.showInputDialog(this, "Número Final", 
                    "WebServices Inutilização", JOptionPane.PLAIN_MESSAGE);
            String eCNPJ = JOptionPane.showInputDialog(this, "CNPJ ou o CPF do autor do Emitente", 
                    "WebServices Inutilização", JOptionPane.PLAIN_MESSAGE);
            String aJustificativa = JOptionPane.showInputDialog(this, "Justificativa", 
                    "WebServices Inutilização", JOptionPane.PLAIN_MESSAGE);
            
            ByteBuffer buffer = ByteBuffer.allocate(256);
            IntByReference bufferLen = new IntByReference(256);
            
            int ret = acbrNFe.NFE_Inutilizar(ACBrNFe.toUTF8(eCNPJ),
                                           ACBrNFe.toUTF8(aJustificativa),
                                           Integer.parseInt(ano),
                                           Integer.parseInt(modelo),
                                           Integer.parseInt(serie),
                                           Integer.parseInt(numeroInicial),
                                           Integer.parseInt(numeroFinal),
                                           buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            if (bufferLen.getValue() > 1024)
            {
                ret = acbrNFe.NFE_UltimoRetorno(buffer, bufferLen);
                ACBrNFe.checkResult(ret);
            }
            
            rtbRespostas.append(ACBrNFe.fromUTF8(buffer, bufferLen));
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInutilizarActionPerformed

    private void btnEnviarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEmailActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("xml", "Arquivo Xml NFe (*.xml)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            String destinatario = JOptionPane.showInputDialog(this, "Digite o email do destinatario", 
                    "Envio email", JOptionPane.PLAIN_MESSAGE);
            
            int ret = acbrNFe.NFE_EnviarEmail(ACBrNFe.toUTF8(destinatario),
                                              ACBrNFe.toUTF8(chooser.getSelectedFile().getAbsolutePath()),
                                              true,
                                              ACBrNFe.toUTF8(txtAssunto.getText()),
                                              ACBrNFe.toUTF8(""),
                                              ACBrNFe.toUTF8(""),
                                              ACBrNFe.toUTF8(txtMensagem.getText()));
            ACBrNFe.checkResult(ret);
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarEmailActionPerformed

    private void btnSelectSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSchemaActionPerformed
        try{
            JFileChooser chooser = new JFileChooser(); 
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Selecione o diretorio");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);           
     
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;            
            txtSchemaPath.setText(chooser.getCurrentDirectory().getPath());
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectSchemaActionPerformed

    private void btnSelectCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCertActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("pfx", "Certificado igital (*.pfx)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            txtCertPath.setText(chooser.getSelectedFile().getPath());
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectCertActionPerformed

    private void loadConfig() {
        try {
            ByteBuffer buffer = ByteBuffer.allocate(256);
            IntByReference bufferLen = new IntByReference(256);

            int ret = acbrNFe.NFE_ConfigLer(ACBrNFe.toUTF8(""));
            ACBrNFe.checkResult(ret);

            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("NFe"), ACBrNFe.toUTF8("ModeloDF"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);

            cmbModeloDocumento.setSelectedIndex(ACBrNFe.parseInt(buffer, bufferLen));
            
            bufferLen.setValue(256);            
            buffer = ByteBuffer.allocate(256);

            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("NFe"), ACBrNFe.toUTF8("IdCSC"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);

            txtIdCSC.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("NFe"), ACBrNFe.toUTF8("CSC"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtCSC.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("SSLCryptLib"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            cmbCrypt.setSelectedIndex(ACBrNFe.parseInt(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("SSLHttpLib"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            cmbHttp.setSelectedIndex(ACBrNFe.parseInt(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("SSLXmlSignLib"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            cmbXmlSign.setSelectedIndex(ACBrNFe.parseInt(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("ArquivoPFX"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtCertPath.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("Senha"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtCertPassword.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("NumeroSerie"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtCertNumero.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("NFe"), ACBrNFe.toUTF8("PathSchemas"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtSchemaPath.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("UF"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            cmbUfDestino.setSelectedItem(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("NFe"), ACBrNFe.toUTF8("Ambiente"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            String ambiente = ACBrNFe.fromUTF8(buffer, bufferLen);
            
            rdbHomologacao.setSelected("1".equals(ambiente));
            rdbProducao.setSelected("0".equals(ambiente));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("NFe"), ACBrNFe.toUTF8("SSLType"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            cmbSSlType.setSelectedIndex(ACBrNFe.parseInt(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("NFe"), ACBrNFe.toUTF8("Timeout"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            nudTimeOut.setValue(ACBrNFe.parseInt(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("Proxy.Host"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtProxyServidor.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("Proxy.Port"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            nudProxyPorta.setValue(ACBrNFe.parseInt(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("Proxy.User"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtProxyUsuario.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("DFe"), ACBrNFe.toUTF8("Proxy.Pass"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtProxySenha.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("Email"), ACBrNFe.toUTF8("Nome"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtNome.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("Email"), ACBrNFe.toUTF8("Conta"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtEmail.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("Email"), ACBrNFe.toUTF8("Usuario"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtUsuario.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("Email"), ACBrNFe.toUTF8("Senha"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtSenha.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("Email"), ACBrNFe.toUTF8("Servidor"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            txtHost.setText(ACBrNFe.fromUTF8(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("Email"), ACBrNFe.toUTF8("Porta"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            nudPorta.setValue(ACBrNFe.parseInt(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("Email"), ACBrNFe.toUTF8("SSL"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            ckbSSL.setSelected(ACBrNFe.parseBoolean(buffer, bufferLen));
            
            bufferLen.setValue(256);
            buffer = ByteBuffer.allocate(256);
            
            ret = acbrNFe.NFE_ConfigLerValor(ACBrNFe.toUTF8("Email"), ACBrNFe.toUTF8("TLS"), buffer, bufferLen);
            ACBrNFe.checkResult(ret);
            
            ckbTLS.setSelected(ACBrNFe.parseBoolean(buffer, bufferLen));

        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveConfig() {
        try {            
            int ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("NFe"), 
                    ACBrNFe.toUTF8("ModeloDF"), 
                    ACBrNFe.toUTF8(cmbModeloDocumento.getSelectedIndex()));
            ACBrNFe.checkResult(ret); 

            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("NFe"), 
                    ACBrNFe.toUTF8("IdCSC"), 
                    ACBrNFe.toUTF8(txtIdCSC.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("NFe"), 
                    ACBrNFe.toUTF8("CSC"), 
                    ACBrNFe.toUTF8(txtCSC.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("SSLCryptLib"), 
                    ACBrNFe.toUTF8(cmbCrypt.getSelectedIndex()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("SSLHttpLib"), 
                    ACBrNFe.toUTF8(cmbHttp.getSelectedIndex()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("SSLXmlSignLib"), 
                    ACBrNFe.toUTF8(cmbXmlSign.getSelectedIndex()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("ArquivoPFX"), 
                    ACBrNFe.toUTF8(txtCertPath.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("Senha"), 
                    ACBrNFe.toUTF8(txtCertPassword.getPassword()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("NumeroSerie"), 
                    ACBrNFe.toUTF8(txtCertNumero.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("NFe"), 
                    ACBrNFe.toUTF8("PathSchemas"), 
                    ACBrNFe.toUTF8(txtSchemaPath.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("UF"), 
                    ACBrNFe.toUTF8(cmbUfDestino.getSelectedItem().toString()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("NFe"), 
                    ACBrNFe.toUTF8("Ambiente"), 
                    ACBrNFe.toUTF8(rdbHomologacao.isSelected() ? "1" : "0"));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("NFe"), 
                    ACBrNFe.toUTF8("SSLType"), 
                    ACBrNFe.toUTF8(cmbSSlType.getSelectedIndex()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("NFe"), 
                    ACBrNFe.toUTF8("Timeout"), 
                    ACBrNFe.toUTF8(nudTimeOut.getValue().toString()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("Proxy.Host"), 
                    ACBrNFe.toUTF8(txtProxyServidor.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("Proxy.Port"), 
                    ACBrNFe.toUTF8(nudProxyPorta.getValue().toString()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("Proxy.User"), 
                    ACBrNFe.toUTF8(txtProxyUsuario.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("DFe"), 
                    ACBrNFe.toUTF8("Proxy.Pass"), 
                    ACBrNFe.toUTF8(txtProxySenha.getPassword()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Email"), 
                    ACBrNFe.toUTF8("Nome"), 
                    ACBrNFe.toUTF8(txtNome.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Email"), 
                    ACBrNFe.toUTF8("Conta"), 
                    ACBrNFe.toUTF8(txtEmail.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Email"), 
                    ACBrNFe.toUTF8("Usuario"), 
                    ACBrNFe.toUTF8(txtUsuario.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Email"), 
                    ACBrNFe.toUTF8("Senha"), 
                    ACBrNFe.toUTF8(txtSenha.getPassword()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Email"), 
                    ACBrNFe.toUTF8("Servidor"), 
                    ACBrNFe.toUTF8(txtHost.getText()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Email"), 
                    ACBrNFe.toUTF8("Porta"), 
                    ACBrNFe.toUTF8(nudPorta.getValue().toString()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Email"), 
                    ACBrNFe.toUTF8("SSL"), 
                    ACBrNFe.toUTF8(ckbSSL.isSelected()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravarValor(ACBrNFe.toUTF8("Email"), 
                    ACBrNFe.toUTF8("TLS"), 
                    ACBrNFe.toUTF8(ckbTLS.isSelected()));
            ACBrNFe.checkResult(ret);
            
            ret = acbrNFe.NFE_ConfigGravar(ACBrNFe.toUTF8(""));
            ACBrNFe.checkResult(ret);
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarNFe;
    private javax.swing.JButton btnConsultaChave;
    private javax.swing.JButton btnConsultaXml;
    private javax.swing.JButton btnConsultarRecibo;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEnviarEmail;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnInutilizar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelectCert;
    private javax.swing.JButton btnSelectSchema;
    private javax.swing.JButton btnStatusServ;
    private javax.swing.JCheckBox ckbSSL;
    private javax.swing.JCheckBox ckbTLS;
    private javax.swing.JComboBox<String> cmbCrypt;
    private javax.swing.JComboBox<String> cmbHttp;
    private javax.swing.JComboBox<String> cmbModeloDocumento;
    private javax.swing.JComboBox<String> cmbSSlType;
    private javax.swing.JComboBox<String> cmbUfDestino;
    private javax.swing.JComboBox<String> cmbXmlSign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner nudPorta;
    private javax.swing.JSpinner nudProxyPorta;
    private javax.swing.JSpinner nudTimeOut;
    private javax.swing.JRadioButton rdbHomologacao;
    private javax.swing.JRadioButton rdbProducao;
    private javax.swing.JTextArea rtbRespostas;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtCSC;
    private javax.swing.JTextField txtCertNumero;
    private javax.swing.JPasswordField txtCertPassword;
    private javax.swing.JTextField txtCertPath;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtIdCSC;
    private javax.swing.JTextArea txtMensagem;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtProxySenha;
    private javax.swing.JTextField txtProxyServidor;
    private javax.swing.JTextField txtProxyUsuario;
    private javax.swing.JTextField txtSchemaPath;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
