namespace ACBrLib.Core
{
    public enum ACBrSessao
    {
        Principal,
        Versao,
        Sistema,
        Proxy,
        Email,
        SoftwareHouse,
        Emissor,
        PosPrinter,
        PosPrinter_Barras,
        PosPrinter_QRCode,
        PosPrinter_Logo,
        PosPrinter_Gaveta,
        ETQ,
        SAT,
        SATConfig,
        SATConfigArquivos,
        SATRede,
        Extrato,
        DFe,
        NFe,
        DANFE,
        DANFENFe,
        DANFENFCe
    }
}