/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acbr.eSocial.demo;

import com.acbr.ACBrSessao;
import com.acbr.esocial.ACBreSocial;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author rften
 */
public class FrmMain extends javax.swing.JFrame {

    private ACBreSocial acbreSocial;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        try {
            acbreSocial = new ACBreSocial();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtbRespostas = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        btnCriarEventoeSocial = new javax.swing.JButton();
        btnEnviareSocial = new javax.swing.JButton();
        btnConsultareSocial = new javax.swing.JButton();
        btnCriarEnviareSocial = new javax.swing.JButton();
        btnLimpareSocial = new javax.swing.JButton();
        btnSetIDEmpregador = new javax.swing.JButton();
        btnSetIDTransmissor = new javax.swing.JButton();
        btnSetTipoEmpregador = new javax.swing.JButton();
        btnSetVersaoDF = new javax.swing.JButton();
        btnDownloadEventos = new javax.swing.JButton();
        btnCarregarXMLEventoeSocial = new javax.swing.JButton();
        btnConsultaIdentificadoresEventosEmpregador = new javax.swing.JButton();
        btnConsultaIdentificadoresEventosTabela = new javax.swing.JButton();
        btnConsultaIdentificadoresEventosTrabalhador = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        ckbAtualizarXML = new javax.swing.JPanel();
        ckbAttXML = new javax.swing.JCheckBox();
        ckbExibirErroSchema = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtFormatoAlerta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbFormaEmissao = new javax.swing.JComboBox<>();
        ckbRetirarAcentos = new javax.swing.JCheckBox();
        ckbSalvar = new javax.swing.JCheckBox();
        txtLogs = new javax.swing.JTextField();
        btnSelectLog = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSchemaPath = new javax.swing.JTextField();
        btnSelectSchema = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        cmbUfDestino = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        cmbSSlType = new javax.swing.JComboBox<>();
        nudTimeOut = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        rdbHomologacao = new javax.swing.JRadioButton();
        rdbProducao = new javax.swing.JRadioButton();
        ckbVisualizar = new javax.swing.JCheckBox();
        ckbSalvarSOAP = new javax.swing.JCheckBox();
        jPanel22 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        txtProxyServidor = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        nudProxyPorta = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        txtProxyUsuario = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtProxySenha = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        ckbAjustarAut = new javax.swing.JCheckBox();
        jLabel43 = new javax.swing.JLabel();
        nudAguardar = new javax.swing.JSpinner();
        jLabel44 = new javax.swing.JLabel();
        nudTentativas = new javax.swing.JSpinner();
        jLabel45 = new javax.swing.JLabel();
        nudIntervalos = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cmbCrypt = new javax.swing.JComboBox<>();
        cmbHttp = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cmbXmlSign = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtCertPath = new javax.swing.JTextField();
        btnSelecionarCertificado = new javax.swing.JButton();
        txtDadosPFX = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtCertNumero = new javax.swing.JTextField();
        txtCertPassword = new javax.swing.JPasswordField();
        btnObterCertificados1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        ckbSalvarArqs = new javax.swing.JCheckBox();
        ckbPastaMensal = new javax.swing.JCheckBox();
        ckbAdicionaLiteral = new javax.swing.JCheckBox();
        ckbEmissaoPatheSocial = new javax.swing.JCheckBox();
        ckbSalvaPathEvento = new javax.swing.JCheckBox();
        ckbSepararPorCNPJ = new javax.swing.JCheckBox();
        ckbSepararPorModelo = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        txtArqeSocial = new javax.swing.JTextField();
        btnArqeSocial = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtEmpregador = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTransmissor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbTipoEmpregador = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbVersaoDF = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnCarregarConfiguracoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACBrLibNFe Demo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(744, 588));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Respostas"));

        rtbRespostas.setColumns(20);
        rtbRespostas.setRows(5);
        jScrollPane1.setViewportView(rtbRespostas);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTabbedPane2.setToolTipText("");
        jTabbedPane2.setName("Envio"); // NOI18N

        btnCriarEventoeSocial.setText("Criar Evento eSocial");
        btnCriarEventoeSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEventoeSocialActionPerformed(evt);
            }
        });

        btnEnviareSocial.setText("Enviar eSocial");
        btnEnviareSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviareSocialActionPerformed(evt);
            }
        });

        btnConsultareSocial.setText("Consultar eSocial");
        btnConsultareSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultareSocialActionPerformed(evt);
            }
        });

        btnCriarEnviareSocial.setText("Criar Enviar eSocial");
        btnCriarEnviareSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEnviareSocialActionPerformed(evt);
            }
        });

        btnLimpareSocial.setText("Limpar eSocial");
        btnLimpareSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpareSocialActionPerformed(evt);
            }
        });

        btnSetIDEmpregador.setText("SetIDEmpregador");
        btnSetIDEmpregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetIDEmpregadorActionPerformed(evt);
            }
        });

        btnSetIDTransmissor.setText("SetIDTransmissor");
        btnSetIDTransmissor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetIDTransmissorActionPerformed(evt);
            }
        });

        btnSetTipoEmpregador.setText("SetTipoEmpregador");
        btnSetTipoEmpregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetTipoEmpregadorActionPerformed(evt);
            }
        });

        btnSetVersaoDF.setText("SetVersaoDF");
        btnSetVersaoDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetVersaoDFActionPerformed(evt);
            }
        });

        btnDownloadEventos.setText("Download Eventos");
        btnDownloadEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadEventosActionPerformed(evt);
            }
        });

        btnCarregarXMLEventoeSocial.setText("Carregar XML Evento eSocial");
        btnCarregarXMLEventoeSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarXMLEventoeSocialActionPerformed(evt);
            }
        });

        btnConsultaIdentificadoresEventosEmpregador.setText("Consulta Identificadores Eventos Empregador");
        btnConsultaIdentificadoresEventosEmpregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaIdentificadoresEventosEmpregadorActionPerformed(evt);
            }
        });

        btnConsultaIdentificadoresEventosTabela.setText("Consulta Identificadores Eventos Tabela");
        btnConsultaIdentificadoresEventosTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaIdentificadoresEventosTabelaActionPerformed(evt);
            }
        });

        btnConsultaIdentificadoresEventosTrabalhador.setText("Consulta Identificadores Eventos Trabalhador");
        btnConsultaIdentificadoresEventosTrabalhador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaIdentificadoresEventosTrabalhadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnConsultaIdentificadoresEventosTrabalhador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultaIdentificadoresEventosTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultaIdentificadoresEventosEmpregador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCriarEventoeSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnviareSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultareSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCriarEnviareSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpareSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSetIDEmpregador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSetIDTransmissor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSetTipoEmpregador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSetVersaoDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDownloadEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarregarXMLEventoeSocial)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarEventoeSocial)
                    .addComponent(btnSetIDEmpregador)
                    .addComponent(btnCarregarXMLEventoeSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviareSocial)
                    .addComponent(btnSetIDTransmissor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultareSocial)
                    .addComponent(btnSetTipoEmpregador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarEnviareSocial)
                    .addComponent(btnSetVersaoDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpareSocial)
                    .addComponent(btnDownloadEventos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultaIdentificadoresEventosEmpregador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultaIdentificadoresEventosTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultaIdentificadoresEventosTrabalhador)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Comandos", jPanel14);

        ckbAttXML.setText("Atualizar XML Cancelado");

        ckbExibirErroSchema.setText("Exibir Erro Schema");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Formato Alerta");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Forma de Emissão");

        cmbFormaEmissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "teNormal", "teContingencia", "teSVCAN", "teDPEC", "teFSDA", "teSCAN", "teSVCRS", "teSVCSP", "teOffLine" }));
        cmbFormaEmissao.setToolTipText("");

        ckbRetirarAcentos.setText("Retirar Acentos dos XMLs enviados");

        ckbSalvar.setText("Salvar Arquivos de Envio e Resposta");

        btnSelectLog.setText("btnSelectLog");
        btnSelectLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectLogActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Pasta dos Logs");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Pasta dos Schemas");

        btnSelectSchema.setText("jButton1");
        btnSelectSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSchemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ckbAtualizarXMLLayout = new javax.swing.GroupLayout(ckbAtualizarXML);
        ckbAtualizarXML.setLayout(ckbAtualizarXMLLayout);
        ckbAtualizarXMLLayout.setHorizontalGroup(
            ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFormatoAlerta)
                    .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                        .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtLogs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectLog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                        .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSchemaPath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectSchema, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                        .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(ckbAttXML)
                            .addComponent(ckbExibirErroSchema)
                            .addComponent(jLabel7)
                            .addComponent(cmbFormaEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbSalvar)
                            .addComponent(ckbRetirarAcentos))
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ckbAtualizarXMLLayout.setVerticalGroup(
            ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ckbAtualizarXMLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckbAttXML)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbExibirErroSchema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFormatoAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFormaEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ckbRetirarAcentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ckbAtualizarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSchemaPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectSchema))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Geral", ckbAtualizarXML);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Uf Destino");

        cmbUfDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("SSL Type");

        cmbSSlType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LT_all", "LT_SSLv2", "LT_SSLv3", "LT_TSLv1", "LT_TSLv1_1", "LT_TSLv1_2", "LT_SSHv2" }));

        nudTimeOut.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("TimeOut");

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ambiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel20.setToolTipText("Ambiente");
        jPanel20.setFocusCycleRoot(true);
        jPanel20.setName("Ambiente"); // NOI18N

        buttonGroup1.add(rdbHomologacao);
        rdbHomologacao.setLabel("Homologação");

        buttonGroup1.add(rdbProducao);
        rdbProducao.setText("Produção");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbHomologacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbProducao)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbProducao)
                    .addComponent(rdbHomologacao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rdbProducao.getAccessibleContext().setAccessibleDescription("");

        ckbVisualizar.setLabel("Visualizar Mensagem");

        ckbSalvarSOAP.setText("Salvar envelope SOAP");

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proxy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel22.setToolTipText("Proxy");
        jPanel22.setName("Ambiente"); // NOI18N

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Servidor");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("Porta");

        nudProxyPorta.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Usuário");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("Senha");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProxyUsuario)
                    .addComponent(txtProxySenha)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProxyServidor)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(nudProxyPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProxyServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nudProxyPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProxyUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProxySenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retorno de Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        ckbAjustarAut.setText("Ajustar Automaticamente prop. \"Aguardar\"");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel43.setText("Aguardar");

        nudAguardar.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Tentativas");

        nudTentativas.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setText("Intervalo");

        nudIntervalos.setModel(new javax.swing.SpinnerNumberModel(5000, 1, null, 1));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nudAguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nudTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nudIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ckbAjustarAut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckbAjustarAut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nudAguardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nudTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nudIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckbSalvarSOAP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbVisualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(cmbUfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(cmbSSlType, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nudTimeOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nudTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSSlType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSalvarSOAP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("WebServices", jPanel6);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("CryptLib");

        cmbCrypt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cryNone", "cryOpenSSL", "cryCapicom", "cryWinCrypt" }));

        cmbHttp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "httpNone", "httpWinINet", "httpWinHttp", "httpOpenSSL", "httpIndy", " ", " ", " " }));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("HttpLib");

        cmbXmlSign.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "xsNone", "xsXmlSec", "xsMsXml", "xsMsXmlCapicom", "xsLibXml2" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("XmlSignLib");

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Certificados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel19.setToolTipText("Certificados");
        jPanel19.setName("DANFe"); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Caminho PFX");

        btnSelecionarCertificado.setText("btnSelectLog");
        btnSelecionarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarCertificadoActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Dados PFX");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Senha");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Número de Série");

        txtCertPassword.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtCertPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionarCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtCertNumero)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(0, 260, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(txtCertPassword)
            .addComponent(txtDadosPFX)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCertPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarCertificado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDadosPFX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(1, 1, 1)
                .addComponent(txtCertPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCertNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnObterCertificados1.setActionCommand("Obter Certificados");
        btnObterCertificados1.setLabel("Obter Certificados");
        btnObterCertificados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObterCertificados1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel17)
                                .addComponent(jLabel26)
                                .addComponent(cmbHttp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbCrypt, 0, 163, Short.MAX_VALUE)
                                .addComponent(jLabel27)
                                .addComponent(cmbXmlSign, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnObterCertificados1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(1, 1, 1)
                .addComponent(cmbCrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbHttp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbXmlSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObterCertificados1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Certificados", jPanel7);

        ckbSalvarArqs.setLabel("Salvar Arquivos em Pastas Separadas");

        ckbPastaMensal.setLabel("Criar Pastas Mensalmente");

        ckbAdicionaLiteral.setLabel("Adicionar Literal no nome das pastas");

        ckbEmissaoPatheSocial.setText("Salvar Documento pelo campo Data de Emissão");

        ckbSalvaPathEvento.setText("Salvar Arquivos de Eventos");

        ckbSepararPorCNPJ.setText("Separar Arqs pelo CNPJ do Certificado");

        ckbSepararPorModelo.setText("Separar Arqs pelo Modelo do Documento");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Pasta Arquivos eSocial");

        btnArqeSocial.setText("btnSelectLog");
        btnArqeSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArqeSocialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 201, Short.MAX_VALUE))
                            .addComponent(txtArqeSocial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArqeSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbSalvarArqs)
                            .addComponent(ckbPastaMensal)
                            .addComponent(ckbAdicionaLiteral)
                            .addComponent(ckbEmissaoPatheSocial)
                            .addComponent(ckbSalvaPathEvento)
                            .addComponent(ckbSepararPorCNPJ)
                            .addComponent(ckbSepararPorModelo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(ckbSalvarArqs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbPastaMensal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbAdicionaLiteral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbEmissaoPatheSocial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSalvaPathEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSepararPorCNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSepararPorModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArqeSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArqeSocial))
                .addGap(0, 223, Short.MAX_VALUE))
        );

        ckbEmissaoPatheSocial.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane3.addTab("Arquivos", jPanel9);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("CNPJ ou CPF do Empregador");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("CNPJ ou CPF do Transmissor");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tipo de Empregador");

        cmbTipoEmpregador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tePessoaJuridica", "teOrgaoPublico", "tePessoaFisica", "teOrgaoPublicoExecutivoFederal", "teOrgaoPublicoLegislativoFederal", "teOrgaoPublicoJudiciarioFederal", "teOrgaoPublicoAutonomoFederal" }));
        cmbTipoEmpregador.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Versão DF");

        cmbVersaoDF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "02_04_01", "02_04_02", "02_05_00", "S01_00_00" }));
        cmbVersaoDF.setToolTipText("");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTransmissor)
                            .addComponent(txtEmpregador)
                            .addComponent(cmbTipoEmpregador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbVersaoDF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel15))
                                .addGap(0, 173, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTransmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoEmpregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbVersaoDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Emitente", jPanel15);

        btnSalvar.setText("Salvar Configurações");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCarregarConfiguracoes.setLabel("Carregar Configurações");
        btnCarregarConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarConfiguracoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCarregarConfiguracoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCarregarConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        btnCarregarConfiguracoes.getAccessibleContext().setAccessibleName("Salvar Carregar Configurações");

        jTabbedPane1.addTab("Configurações", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addGap(49, 49, 49))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Envio");

        setSize(new java.awt.Dimension(880, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            // Altera as config de log
            Path pathLog = Paths.get(System.getProperty("user.dir"), "Log");
            if (!Files.isDirectory(pathLog)) {
                pathLog.toFile().mkdirs();
            }

            acbreSocial.configGravarValor(ACBrSessao.Principal, "LogNivel", 4);
            acbreSocial.configGravarValor(ACBrSessao.Principal, "LogPath", pathLog.toString());
            acbreSocial.configGravar();

            loadConfig();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated
 
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        saveConfig();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCarregarConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarConfiguracoesActionPerformed
        loadConfig();
    }//GEN-LAST:event_btnCarregarConfiguracoesActionPerformed

    private void btnSelectLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectLogActionPerformed

        try{
            JFileChooser chooser = new JFileChooser(); 
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Selecione o diretorio");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);           
     
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;            
            txtLogs.setText(chooser.getSelectedFile().toString());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "PathSalvar", txtLogs.getText()); 
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectLogActionPerformed

    private void btnSelectSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSchemaActionPerformed

       try{
            JFileChooser chooser = new JFileChooser(); 
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Selecione o diretorio");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);           
     
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;            
            txtSchemaPath.setText(chooser.getSelectedFile().toString());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "PathSchemas", txtSchemaPath.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }       
        
    }//GEN-LAST:event_btnSelectSchemaActionPerformed

    private void btnArqeSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArqeSocialActionPerformed

        try{
            JFileChooser chooser = new JFileChooser(); 
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Selecione o diretorio");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);           
     
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;            
            txtArqeSocial.setText(chooser.getSelectedFile().toString());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "PatheSocial", txtArqeSocial.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnArqeSocialActionPerformed

    private void btnSelecionarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarCertificadoActionPerformed

       try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("pfx", "Certificado Digital (*.pfx)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            txtCertPath.setText(chooser.getSelectedFile().toString());
            acbreSocial.configGravarValor(ACBrSessao.DFe, "ArquivoPFX", txtCertPath.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSelecionarCertificadoActionPerformed

    private void btnCriarEventoeSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEventoeSocialActionPerformed
        try 
        {
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("ini", "Arquivo ini (*.ini)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            acbreSocial.criarEventoeSocial(chooser.getSelectedFile().getAbsolutePath());
            rtbRespostas.append("dados carregados."); 
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCriarEventoeSocialActionPerformed

    private void btnEnviareSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviareSocialActionPerformed
        try 
        {
             String aGrupo = JOptionPane.showInputDialog("Digite o Grupo");
             int grupo = Integer.parseInt(aGrupo);
             
             String ret = acbreSocial.enviareSocial(grupo);
             rtbRespostas.append(ret);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviareSocialActionPerformed

    private void btnConsultareSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultareSocialActionPerformed
        try 
        {
            String eProtocolo = JOptionPane.showInputDialog("Digite o Protocolo");
            
            String ret = acbreSocial.consultareSocial(eProtocolo);
            rtbRespostas.append(ret);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultareSocialActionPerformed

    private void btnCriarEnviareSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEnviareSocialActionPerformed
        try 
        {
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("ini", "Arquivo ini (*.ini)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            String aGrupo = JOptionPane.showInputDialog("Digite o Grupo");
            int grupo = Integer.parseInt(aGrupo);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            acbreSocial.criarEnviareSocial(chooser.getSelectedFile().getAbsolutePath(), grupo);
        } 
        catch (Exception ex) 
        {
            
        }
    }//GEN-LAST:event_btnCriarEnviareSocialActionPerformed

    private void btnLimpareSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpareSocialActionPerformed
        try{
            acbreSocial.limpareSocial();
            rtbRespostas.append("Lista Limpa"); 
            
        }catch (Exception ex){
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLimpareSocialActionPerformed

    private void btnCarregarXMLEventoeSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarXMLEventoeSocialActionPerformed
        try 
        {
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("xml", "Arquivo xml (*.xml)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            
            if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
            acbreSocial.carregarXMLEventoeSocial(chooser.getSelectedFile().getAbsolutePath());
            rtbRespostas.append("xml carregado."); 
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCarregarXMLEventoeSocialActionPerformed

    private void btnSetIDEmpregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetIDEmpregadorActionPerformed
        try 
        {
            acbreSocial.setIDEmpregador(txtEmpregador.getText());
        } 
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetIDEmpregadorActionPerformed

    private void btnSetIDTransmissorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetIDTransmissorActionPerformed
        try 
        {
            acbreSocial.setIDTransmissor(txtTransmissor.getText());
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetIDTransmissorActionPerformed

    private void btnSetTipoEmpregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetTipoEmpregadorActionPerformed
        try
        {
            acbreSocial.setTipoEmpregador(cmbTipoEmpregador.getSelectedIndex());
        }
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetTipoEmpregadorActionPerformed

    private void btnSetVersaoDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetVersaoDFActionPerformed
        try
        {
            acbreSocial.setVersaoDF(cmbVersaoDF.toString());
        }
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetVersaoDFActionPerformed

    private void btnConsultaIdentificadoresEventosEmpregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaIdentificadoresEventosEmpregadorActionPerformed
        try 
        {
            int tipoEvento = Integer.parseInt(JOptionPane.showInputDialog("Informe o Tipo do Evento"));
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date dPeriodoApuracao = sdf.parse(JOptionPane.showInputDialog("Informe o período de apuração"));
            
            double TDateTimePeriodoApuracao = acbreSocial.convertDateToTDateTime(dPeriodoApuracao);
            
            String ret = acbreSocial.consultaIdentificadoresEventosEmpregador(txtEmpregador.getText(), tipoEvento, TDateTimePeriodoApuracao);
            rtbRespostas.append(ret);
        }
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultaIdentificadoresEventosEmpregadorActionPerformed

    private void btnConsultaIdentificadoresEventosTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaIdentificadoresEventosTabelaActionPerformed
        try
        {
            int aTipoEvento = Integer.parseInt(JOptionPane.showInputDialog("Informe o Tipo do Evento"));
            String chave = JOptionPane.showInputDialog("Informe a Chave");
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date dDataInicial = sdf.parse(JOptionPane.showInputDialog("Informe a data inicial"));
            Date dDataFinal = sdf.parse(JOptionPane.showInputDialog("Informe a data final"));
            
            double TDateTimeInicio = acbreSocial.convertDateToTDateTime(dDataInicial);
            double TDateTimeFinal = acbreSocial.convertDateToTDateTime(dDataFinal);
            
            String ret = acbreSocial.consultaIdentificadoresEventosTabela(txtEmpregador.getText(), aTipoEvento, chave, TDateTimeInicio, TDateTimeFinal);
            rtbRespostas.append(ret);
        }
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultaIdentificadoresEventosTabelaActionPerformed

    private void btnConsultaIdentificadoresEventosTrabalhadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaIdentificadoresEventosTrabalhadorActionPerformed
        try
        {
            String cpfTrabalhador = JOptionPane.showInputDialog("Informe o CPF do trabalhador");
            
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
            Date dDataInicial = sdf.parse(JOptionPane.showInputDialog("Informe a data inicial"));
            Date dDataFinal = sdf.parse(JOptionPane.showInputDialog("Informe a data final"));
            
            double TDateTimeInicio = acbreSocial.convertDateToTDateTime(dDataInicial);
            double TDateTimeFinal = acbreSocial.convertDateToTDateTime(dDataFinal);
            
            String ret = acbreSocial.consultaIdentificadoresEventosTrabalhador(txtEmpregador.getText(), cpfTrabalhador, TDateTimeInicio, TDateTimeFinal);
            rtbRespostas.append(ret);
        }
        catch (Exception ex)
        {
           Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }//GEN-LAST:event_btnConsultaIdentificadoresEventosTrabalhadorActionPerformed

    private void btnDownloadEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadEventosActionPerformed
        try 
        {
            String cpfTrabalhador = JOptionPane.showInputDialog("Informe o CPF do trabalhador");
           
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
            Date dDataInicial = sdf.parse(JOptionPane.showInputDialog("Informe a data inicial"));
            Date dDataFinal = sdf.parse(JOptionPane.showInputDialog("Informe a data final"));
            
            double TDateTimeInicial = acbreSocial.convertDateToTDateTime(dDataInicial);
            double TDateTimeFinal = acbreSocial.convertDateToTDateTime(dDataFinal);
            
            String ret = acbreSocial.downloadEventos(txtEmpregador.getText(), cpfTrabalhador, TDateTimeInicial, TDateTimeFinal);
            rtbRespostas.append(ret);
        }
        catch (Exception ex)
        {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDownloadEventosActionPerformed

    private void btnObterCertificados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObterCertificados1ActionPerformed

        try {
            String ret = acbreSocial.obterCertificados();
            rtbRespostas.append(ret);
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnObterCertificados1ActionPerformed

    private void loadConfig() {
        try {
            
            acbreSocial.configLer();
            
            //Config Geral
            ckbExibirErroSchema.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "ExibirErroSchema").equals("1"));
            txtFormatoAlerta.setText(acbreSocial.configLerValor(ACBrSessao.eSocial, "FormatoAlerta"));
            cmbFormaEmissao.setSelectedIndex(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.eSocial, "FormaEmissao")));  
            ckbRetirarAcentos.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "RetirarAcentos").equals("1"));
            ckbSalvar.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "SalvarGer").equals("1"));
            txtLogs.setText(acbreSocial.configLerValor(ACBrSessao.eSocial, "PathSalvar"));
            txtSchemaPath.setText(acbreSocial.configLerValor(ACBrSessao.eSocial, "PathSchemas"));
            txtEmpregador.setText(acbreSocial.configLerValor(ACBrSessao.eSocial, "IdEmpregador"));
            txtTransmissor.setText(acbreSocial.configLerValor(ACBrSessao.eSocial, "IdTransmissor"));
            cmbTipoEmpregador.setSelectedIndex(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.eSocial, "TipoEmpregador")));
            cmbVersaoDF.setSelectedIndex(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.eSocial, "VersaoDF")));
            
            //Config WebService
            cmbUfDestino.setSelectedItem(acbreSocial.configLerValor(ACBrSessao.DFe, "UF"));
            cmbSSlType.setSelectedIndex(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.eSocial, "SSLType")));
            nudTimeOut.setValue(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.eSocial, "Timeout")));
            
            String ambiente = acbreSocial.configLerValor(ACBrSessao.eSocial, "Ambiente");            
            rdbHomologacao.setSelected("1".equals(ambiente));
            rdbProducao.setSelected("0".equals(ambiente));            
            
            ckbVisualizar.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "Visualizar").equals("1"));
            ckbSalvarSOAP.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "SalvarWS").equals("1"));
            ckbAjustarAut.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "AjustaAguardaConsultaRet").equals("1"));
            nudAguardar.setValue(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.eSocial, "AguardarConsultaRet")));
            nudTentativas.setValue(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.eSocial, "Tentativas")));
            nudIntervalos.setValue(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.eSocial, "IntervaloTentativas")));
            
            txtProxyServidor.setText(acbreSocial.configLerValor(ACBrSessao.Proxy, "Servidor"));
            
            String Value = acbreSocial.configLerValor(ACBrSessao.Proxy, "Porta");        
            if(Value.matches("-?\\d+"))
              nudProxyPorta.setValue(Integer.parseInt(Value));           
            
            txtProxyUsuario.setText(acbreSocial.configLerValor(ACBrSessao.Proxy, "Usuario"));
            txtProxySenha.setText(acbreSocial.configLerValor(ACBrSessao.Proxy, "Senha"));
            
            //Config Certificado
            cmbCrypt.setSelectedIndex(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.DFe, "SSLCryptLib")));            
            cmbHttp.setSelectedIndex(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.DFe, "SSLHttpLib")));    
            cmbXmlSign.setSelectedIndex(Integer.parseInt(acbreSocial.configLerValor(ACBrSessao.DFe, "SSLXmlSignLib")));
            txtCertPath.setText(acbreSocial.configLerValor(ACBrSessao.DFe, "ArquivoPFX"));
            txtCertPassword.setText(acbreSocial.configLerValor(ACBrSessao.DFe, "Senha"));
            txtCertNumero.setText(acbreSocial.configLerValor(ACBrSessao.DFe, "NumeroSerie"));
            txtDadosPFX.setText(acbreSocial.configLerValor(ACBrSessao.DFe, "DadosPFX"));
            
            //Config Arquivos
   
            ckbSalvarArqs.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "SalvarGer").equals("1"));
            ckbPastaMensal.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "SepararPorMes").equals("1"));
            ckbAdicionaLiteral.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "AdicionarLiteral").equals("1"));
            ckbSalvaPathEvento.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "SalvarArq").equals("1"));            
            ckbSepararPorCNPJ.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "SepararPorCNPJ").equals("1"));
            ckbSepararPorModelo.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "SepararPorModelo").equals("1"));
            ckbEmissaoPatheSocial.setSelected(acbreSocial.configLerValor(ACBrSessao.eSocial, "EmissaoPatheSocial").equals("1"));
            txtArqeSocial.setText(acbreSocial.configLerValor(ACBrSessao.eSocial, "PatheSocial"));
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveConfig() {
        try {
            
            //Config Geral
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "ExibirErroSchema", ckbExibirErroSchema.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "FormatoAlerta", txtFormatoAlerta.getText());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "FormaEmissao", cmbFormaEmissao.getSelectedIndex());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "RetirarAcentos", ckbRetirarAcentos.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "SalvarWS", ckbSalvar.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "PathSalvar", txtLogs.getText());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "PathSchemas", txtSchemaPath.getText());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "IdEmpregador", txtEmpregador.getText());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "IdTransmissor", txtTransmissor.getText());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "TipoEmpregador", cmbTipoEmpregador.getSelectedIndex());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "VersaoDF", cmbVersaoDF.getSelectedIndex());
                        
            // Config WebService
            acbreSocial.configGravarValor(ACBrSessao.DFe, "UF", cmbUfDestino.getSelectedItem().toString());
            
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "SSLType", cmbSSlType.getSelectedIndex());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "Timeout", nudTimeOut.getValue().toString());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "Ambiente", rdbHomologacao.isSelected() ? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "Visualizar", ckbVisualizar.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "SalvarWS", ckbSalvarSOAP.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "AjustaAguardaConsultaRet", ckbAjustarAut.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "AguardarConsultaRet", nudAguardar.getValue().toString());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "Tentativas", nudTentativas.getValue().toString());
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "IntervaloTentativas", nudIntervalos.getValue().toString());
            
            acbreSocial.configGravarValor(ACBrSessao.Proxy, "Servidor", txtProxyServidor.getText());
            acbreSocial.configGravarValor(ACBrSessao.Proxy, "Porta", nudProxyPorta.getValue().toString());
            acbreSocial.configGravarValor(ACBrSessao.Proxy, "Usuario", txtProxyUsuario.getText());
            acbreSocial.configGravarValor(ACBrSessao.Proxy, "Senha", txtProxySenha.getText());
            
            //Config Certificado
            acbreSocial.configGravarValor(ACBrSessao.DFe, "SSLCryptLib", cmbCrypt.getSelectedIndex());            
            acbreSocial.configGravarValor(ACBrSessao.DFe, "SSLHttpLib", cmbHttp.getSelectedIndex());           
            acbreSocial.configGravarValor(ACBrSessao.DFe, "SSLXmlSignLib", cmbXmlSign.getSelectedIndex());            
            acbreSocial.configGravarValor(ACBrSessao.DFe, "ArquivoPFX", txtCertPath.getText());     
            acbreSocial.configGravarValor(ACBrSessao.DFe, "Senha", new String(txtCertPassword.getPassword()));
            acbreSocial.configGravarValor(ACBrSessao.DFe, "NumeroSerie", txtCertNumero.getText());
            acbreSocial.configGravarValor(ACBrSessao.DFe, "DadosPFX", txtDadosPFX.getText());            
            
            //Config Arquivos
           
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "SalvarGer", ckbSalvarArqs.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "SepararPorMes",ckbPastaMensal.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "AdicionarLiteral", ckbAdicionaLiteral.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "EmissaoPatheSocial", ckbEmissaoPatheSocial.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "SalvarArq", ckbSalvaPathEvento.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "SepararPorCNPJ", ckbSepararPorCNPJ.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "SepararPorModelo", ckbSepararPorModelo.isSelected()? "1" : "0");
            acbreSocial.configGravarValor(ACBrSessao.eSocial, "PatheSocial", txtArqeSocial.getText());
            
            acbreSocial.configGravar();            
            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArqeSocial;
    private javax.swing.JButton btnCarregarConfiguracoes;
    private javax.swing.JButton btnCarregarXMLEventoeSocial;
    private javax.swing.JButton btnConsultaIdentificadoresEventosEmpregador;
    private javax.swing.JButton btnConsultaIdentificadoresEventosTabela;
    private javax.swing.JButton btnConsultaIdentificadoresEventosTrabalhador;
    private javax.swing.JButton btnConsultareSocial;
    private javax.swing.JButton btnCriarEnviareSocial;
    private javax.swing.JButton btnCriarEventoeSocial;
    private javax.swing.JButton btnDownloadEventos;
    private javax.swing.JButton btnEnviareSocial;
    private javax.swing.JButton btnLimpareSocial;
    private javax.swing.JButton btnObterCertificados;
    private javax.swing.JButton btnObterCertificados1;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionarCertificado;
    private javax.swing.JButton btnSelectLog;
    private javax.swing.JButton btnSelectSchema;
    private javax.swing.JButton btnSetIDEmpregador;
    private javax.swing.JButton btnSetIDTransmissor;
    private javax.swing.JButton btnSetTipoEmpregador;
    private javax.swing.JButton btnSetVersaoDF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox ckbAdicionaLiteral;
    private javax.swing.JCheckBox ckbAjustarAut;
    private javax.swing.JCheckBox ckbAttXML;
    private javax.swing.JPanel ckbAtualizarXML;
    private javax.swing.JCheckBox ckbEmissaoPatheSocial;
    private javax.swing.JCheckBox ckbExibirErroSchema;
    private javax.swing.JCheckBox ckbPastaMensal;
    private javax.swing.JCheckBox ckbRetirarAcentos;
    private javax.swing.JCheckBox ckbSalvaPathEvento;
    private javax.swing.JCheckBox ckbSalvar;
    private javax.swing.JCheckBox ckbSalvarArqs;
    private javax.swing.JCheckBox ckbSalvarSOAP;
    private javax.swing.JCheckBox ckbSepararPorCNPJ;
    private javax.swing.JCheckBox ckbSepararPorModelo;
    private javax.swing.JCheckBox ckbVisualizar;
    private javax.swing.JComboBox<String> cmbCrypt;
    private javax.swing.JComboBox<String> cmbFormaEmissao;
    private javax.swing.JComboBox<String> cmbHttp;
    private javax.swing.JComboBox<String> cmbSSlType;
    private javax.swing.JComboBox<String> cmbTipoEmpregador;
    private javax.swing.JComboBox<String> cmbUfDestino;
    private javax.swing.JComboBox<String> cmbVersaoDF;
    private javax.swing.JComboBox<String> cmbXmlSign;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JSpinner nudAguardar;
    private javax.swing.JSpinner nudIntervalos;
    private javax.swing.JSpinner nudProxyPorta;
    private javax.swing.JSpinner nudTentativas;
    private javax.swing.JSpinner nudTimeOut;
    private javax.swing.JRadioButton rdbHomologacao;
    private javax.swing.JRadioButton rdbProducao;
    private javax.swing.JTextArea rtbRespostas;
    private javax.swing.JTextField txtArqeSocial;
    private javax.swing.JTextField txtCertNumero;
    private javax.swing.JPasswordField txtCertPassword;
    private javax.swing.JTextField txtCertPath;
    private javax.swing.JTextField txtDadosPFX;
    private javax.swing.JTextField txtEmpregador;
    private javax.swing.JTextField txtFormatoAlerta;
    private javax.swing.JTextField txtLogs;
    private javax.swing.JTextField txtProxySenha;
    private javax.swing.JTextField txtProxyServidor;
    private javax.swing.JTextField txtProxyUsuario;
    private javax.swing.JTextField txtSchemaPath;
    private javax.swing.JTextField txtTransmissor;
    // End of variables declaration//GEN-END:variables
}
