/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acbr.sat.demo;

import com.acbr.ACBrSessao;
import com.acbr.NivelLog;
import com.acbr.dfe.TipoRelatorioBobina;
import com.acbr.posprinter.ACBrPosPrinterModelo;
import com.acbr.posprinter.PosPaginaCodigo;
import com.acbr.sat.ACBrSat;
import com.acbr.sat.SATModelo;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;

/**
 *
 * @author rften
 */
public class FrmMain extends javax.swing.JFrame {
    
    private ACBrSat acbrSat;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        try {
            acbrSat = new ACBrSat();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDllPath = new javax.swing.JTextField();
        btnSelDll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbModeloSat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtAtivacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nudVersaoCFe = new javax.swing.JSpinner();
        nudPaginaCodigo = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSignAc = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        chkSaveCFe = new javax.swing.JCheckBox();
        chkSaveEnvio = new javax.swing.JCheckBox();
        chkSaveCFeCanc = new javax.swing.JCheckBox();
        chkSepararCNPJ = new javax.swing.JCheckBox();
        chkSepararData = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbImpressao = new javax.swing.JComboBox<>();
        txtSoftwareHouse = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nudCopias = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        cmbImpressora = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        chkSetup = new javax.swing.JCheckBox();
        chkPreview = new javax.swing.JCheckBox();
        chkUsaCodigoEanImpressao = new javax.swing.JCheckBox();
        chkImprimeEmUmaLinha = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        cbbModelo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbbPortas = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbbPaginaCodigo = new javax.swing.JComboBox<>();
        nudColunas = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nudEspacos = new javax.swing.JSpinner();
        nudBuffer = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        nudLinhasPular = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        cbxCortarPapel = new javax.swing.JCheckBox();
        cbxControlePorta = new javax.swing.JCheckBox();
        cbxTraduzirTags = new javax.swing.JCheckBox();
        cbxIgnorarTags = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        nudPorta = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        ckbSSL = new javax.swing.JCheckBox();
        ckbTLS = new javax.swing.JCheckBox();
        txtSenha = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtbRespostas = new javax.swing.JTextArea();
        btnIniDesini = new javax.swing.JButton();
        btnCriarCFe = new javax.swing.JButton();
        btnCriarEnviarCFe = new javax.swing.JButton();
        btnEnviarCFe = new javax.swing.JButton();
        btnImprimirCFe = new javax.swing.JButton();
        btnImprimirPDFCFe = new javax.swing.JButton();
        btnImprimiCFeRed = new javax.swing.JButton();
        btnConsultarSAT = new javax.swing.JButton();
        btnConsultarStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACBrLibSat Demo");
        setPreferredSize(new java.awt.Dimension(758, 456));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome Dll");

        txtDllPath.setText("C:\\SAT\\SAT.dll");
        txtDllPath.setPreferredSize(new java.awt.Dimension(269, 20));

        btnSelDll.setLabel("...");
        btnSelDll.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Modelo");

        cmbModeloSat.setModel(new DefaultComboBoxModel<>(SATModelo.values()));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Codigo Ativação");

        txtAtivacao.setText("123456");
        txtAtivacao.setPreferredSize(new java.awt.Dimension(269, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Versão");

        nudVersaoCFe.setModel(new javax.swing.SpinnerNumberModel(0.07d, null, null, 0.01d));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Pagina de Codigo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("SignAC");

        txtSignAc.setText("123456");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Salvar XMLs"));

        chkSaveCFe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkSaveCFe.setSelected(true);
        chkSaveCFe.setText("Salvar CFe");

        chkSaveEnvio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkSaveEnvio.setSelected(true);
        chkSaveEnvio.setText("Salvar Envio");

        chkSaveCFeCanc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkSaveCFeCanc.setSelected(true);
        chkSaveCFeCanc.setText("Salvar CFeCanc");

        chkSepararCNPJ.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkSepararCNPJ.setSelected(true);
        chkSepararCNPJ.setText("Separar Por CNPJ");

        chkSepararData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkSepararData.setSelected(true);
        chkSepararData.setText("Separar Por Data");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSaveCFe)
                    .addComponent(chkSaveEnvio)
                    .addComponent(chkSaveCFeCanc)
                    .addComponent(chkSepararCNPJ)
                    .addComponent(chkSepararData)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(chkSaveCFe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSaveEnvio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSaveCFeCanc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSepararCNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSepararData)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtDllPath, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSelDll, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)
                                .addComponent(txtAtivacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(cmbModeloSat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nudVersaoCFe, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(nudPaginaCodigo)))))
                    .addComponent(jLabel6)
                    .addComponent(txtSignAc, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDllPath, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelDll, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbModeloSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAtivacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nudVersaoCFe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nudPaginaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSignAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configuração CFe", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tipo Impressão");

        cmbImpressao.setModel(new DefaultComboBoxModel<>(TipoRelatorioBobina.values()));

        txtSoftwareHouse.setText("Projeto ACBr");
        txtSoftwareHouse.setPreferredSize(new java.awt.Dimension(269, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Software House");

        nudCopias.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nº de Copias");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Site");

        txtSite.setText("http://www.projetoacbr.com.br");
        txtSite.setPreferredSize(new java.awt.Dimension(269, 20));

        cmbImpressora.setEditable(true);
        cmbImpressora.setSelectedItem("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Impressora");

        chkSetup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkSetup.setText("Mostrar Setup");

        chkPreview.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkPreview.setText("Mostrar Preview");

        chkUsaCodigoEanImpressao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkUsaCodigoEanImpressao.setText("Usar Codigo Ean");

        chkImprimeEmUmaLinha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkImprimeEmUmaLinha.setText("Imprime Em Uma Linha");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PosPrinter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cbbModelo.setModel(new DefaultComboBoxModel<>(ACBrPosPrinterModelo.values()));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Modelo");

        cbbPortas.setEditable(true);
        cbbPortas.setSelectedItem("");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Impressora");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Pag. Código");
        jLabel14.setToolTipText("");

        cbbPaginaCodigo.setModel(new DefaultComboBoxModel<>(PosPaginaCodigo.values()));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Colunas");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Espaços");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Buffer");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Linhas Pular");

        cbxCortarPapel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxCortarPapel.setSelected(true);
        cbxCortarPapel.setText("Cortar Papel");

        cbxControlePorta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxControlePorta.setText("Controle Porta");

        cbxTraduzirTags.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxTraduzirTags.setSelected(true);
        cbxTraduzirTags.setText("Traduzir Tags");

        cbxIgnorarTags.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbxIgnorarTags.setText("Ignorar Tags");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(cbbPaginaCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nudColunas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nudEspacos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nudBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nudLinhasPular)))
                    .addComponent(cbbPortas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxControlePorta)
                    .addComponent(cbxCortarPapel)
                    .addComponent(cbxTraduzirTags)
                    .addComponent(cbxIgnorarTags))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPaginaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nudColunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nudEspacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nudBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nudLinhasPular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxControlePorta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCortarPapel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTraduzirTags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxIgnorarTags)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nudCopias)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbImpressao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtSoftwareHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(cmbImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPreview)
                            .addComponent(chkSetup))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkUsaCodigoEanImpressao)
                            .addComponent(chkImprimeEmUmaLinha))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSoftwareHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbImpressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nudCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkPreview)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkSetup))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkUsaCodigoEanImpressao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkImprimeEmUmaLinha)))))
                .addContainerGap())
        );

        jLabel8.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Impressão", jPanel2);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Nome");

        txtNome.setPreferredSize(new java.awt.Dimension(269, 20));

        txtUsuario.setPreferredSize(new java.awt.Dimension(269, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Usuário");
        jLabel20.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Senha");
        jLabel21.setToolTipText("");

        txtEmail.setPreferredSize(new java.awt.Dimension(269, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Email");

        txtHost.setPreferredSize(new java.awt.Dimension(269, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Host");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Porta");

        ckbSSL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbSSL.setText("SSL");

        ckbTLS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckbTLS.setText("TLS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txtSenha)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(nudPorta, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbSSL)
                    .addComponent(ckbTLS))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbSSL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbTLS))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nudPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Email", null, jPanel3, "");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Respostas"));

        rtbRespostas.setColumns(20);
        rtbRespostas.setRows(5);
        jScrollPane1.setViewportView(rtbRespostas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );

        btnIniDesini.setText("Inicializar");
        btnIniDesini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniDesiniActionPerformed(evt);
            }
        });

        btnCriarCFe.setText("Criar CFe");
        btnCriarCFe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarCFeActionPerformed(evt);
            }
        });

        btnCriarEnviarCFe.setText("Criar Enviar CFe");
        btnCriarEnviarCFe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEnviarCFeActionPerformed(evt);
            }
        });

        btnEnviarCFe.setText("Enviar CFe");
        btnEnviarCFe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCFeActionPerformed(evt);
            }
        });

        btnImprimirCFe.setText("Imprimir CFe");
        btnImprimirCFe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirCFeActionPerformed(evt);
            }
        });

        btnImprimirPDFCFe.setText("Imprimir PDF CFe");
        btnImprimirPDFCFe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirPDFCFeActionPerformed(evt);
            }
        });

        btnImprimiCFeRed.setText("Imprimir CFe Red.");
        btnImprimiCFeRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimiCFeRedActionPerformed(evt);
            }
        });

        btnConsultarSAT.setText("Consultar SAT");
        btnConsultarSAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSATActionPerformed(evt);
            }
        });

        btnConsultarStatus.setText("Consultar Status");
        btnConsultarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniDesini, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCriarCFe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCriarEnviarCFe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEnviarCFe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnImprimirCFe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnImprimiCFeRed, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnImprimirPDFCFe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultarSAT, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniDesini)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarSAT)
                            .addComponent(btnConsultarStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCriarCFe)
                            .addComponent(btnCriarEnviarCFe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviarCFe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnImprimirCFe)
                            .addComponent(btnImprimiCFeRed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimirPDFCFe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 809, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            cbbPortas.addItem("LPT1");
            cbbPortas.addItem("LPT2");
            cbbPortas.addItem("\\\\localhost\\Epson");
            cbbPortas.addItem("c:\\temp\\posprinter.txt");
            
            cbbPortas.setSelectedIndex(cbbPortas.getItemCount() -1);
            
            PrintService[] printServices = PrintServiceLookup.lookupPrintServices(null, null);
            for (PrintService printer : printServices){
                cmbImpressora.addItem(printer.getName());
                cbbPortas.addItem(printer.getName());
            }
            
            if(printServices.length > 0)
                cmbImpressora.setSelectedIndex(0);
                                   
            // Altera as config de log
            Path path = Paths.get(System.getProperty("user.dir"), "Logs");
            if (!Files.isDirectory(path)) {
                path.toFile().mkdirs();
            }
            
            acbrSat.configGravarValor(ACBrSessao.Principal, "LogNivel", NivelLog.logParanoico);  
            acbrSat.configGravarValor(ACBrSessao.Principal, "LogPath", path);
            acbrSat.configGravar();
            loadConfig();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnIniDesiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniDesiniActionPerformed
        try {
            if("Inicializar".equals(btnIniDesini.getText())){
                saveConfig();
                acbrSat.inicializar();                
                btnIniDesini.setText("Desinicializar");
            }else{
                acbrSat.desInicializar();
                btnIniDesini.setText("Inicializar");
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIniDesiniActionPerformed

    private void btnCriarCFeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarCFeActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("png", "Arquivos PNG (*.png)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            int returnVal = chooser.showSaveDialog(rootPane);
            if (returnVal != JFileChooser.APPROVE_OPTION) return;
            
            String ret = acbrSat.criarCFe(chooser.getSelectedFile().getAbsolutePath());
            rtbRespostas.append(ret);            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCriarCFeActionPerformed

    private void btnCriarEnviarCFeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEnviarCFeActionPerformed
        try{            
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("ini", "Ini File (*.ini)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            int returnVal = chooser.showSaveDialog(rootPane);
            if (returnVal != JFileChooser.APPROVE_OPTION) return;
            
            String ret = acbrSat.criarEnviarCFe(chooser.getSelectedFile().getPath());
            rtbRespostas.append(ret);
        } catch (Exception ex) {            
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCriarEnviarCFeActionPerformed

    private void btnEnviarCFeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCFeActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("xml", "Arquivo Xml CFe (*.xml)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            int returnVal = chooser.showSaveDialog(rootPane);
            if (returnVal != JFileChooser.APPROVE_OPTION) return;
                        
            String ret = acbrSat.enviarCFe(chooser.getSelectedFile().getPath());
            rtbRespostas.append(ret);
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarCFeActionPerformed

    private void btnImprimirCFeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirCFeActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("xml", "Arquivo Xml CFe (*.xml)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            int returnVal = chooser.showSaveDialog(rootPane);
            if (returnVal != JFileChooser.APPROVE_OPTION) return;
                                   
            acbrSat.imprimirExtratoVenda(chooser.getSelectedFile().getAbsolutePath());
            rtbRespostas.append("Impressão efetuada com sucesso.");
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirCFeActionPerformed

    private void btnImprimiCFeRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimiCFeRedActionPerformed
        try{            
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("xml", "Arquivo Xml CFe (*.xml)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            int returnVal = chooser.showSaveDialog(rootPane);
            if (returnVal != JFileChooser.APPROVE_OPTION) return;
                                  
            acbrSat.imprimirExtratoResumido(chooser.getSelectedFile().getAbsolutePath());
            rtbRespostas.append("Impressão efetuada com sucesso.");
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimiCFeRedActionPerformed

    private void btnImprimirPDFCFeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirPDFCFeActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
            OpenFileFilter filter = new OpenFileFilter("xml", "Arquivo Xml CFe (*.xml)");
            chooser.addChoosableFileFilter(filter);
            chooser.setFileFilter(filter);
            int returnVal = chooser.showSaveDialog(rootPane);
            if (returnVal != JFileChooser.APPROVE_OPTION) return;
                                   
            String ret = acbrSat.gerarPDFExtratoVenda(chooser.getSelectedFile().getAbsolutePath());
            rtbRespostas.append(ret);           
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirPDFCFeActionPerformed

    private void btnConsultarSATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSATActionPerformed
        try
        {
            String ret = acbrSat.consultarSAT();
            rtbRespostas.append(ret);              
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarSATActionPerformed

    private void btnConsultarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarStatusActionPerformed
        try
        {
            String ret = acbrSat.consultarStatusOperacional();
            rtbRespostas.append(ret);
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarStatusActionPerformed

    private void loadConfig(){
        try{            
            acbrSat.configLer();
            
            String ret = acbrSat.configLerValor(ACBrSessao.SAT, "NomeDLL");                      
            txtDllPath.setText(ret);

            ret = acbrSat.configLerValor(ACBrSessao.SAT, "Modelo");
            cmbModeloSat.setSelectedItem(SATModelo.valueOf(Integer.parseInt(ret)));

            ret = acbrSat.configLerValor(ACBrSessao.SAT, "CodigoDeAtivacao");                        
            txtAtivacao.setText(ret);

            ret = acbrSat.configLerValor(ACBrSessao.SATConfig, "infCFe_versaoDadosEnt");
            NumberFormat format = NumberFormat.getInstance(Locale.FRANCE);
            nudVersaoCFe.setValue(format.parse(ret));

            ret = acbrSat.configLerValor(ACBrSessao.SATConfig, "PaginaDeCodigo");
            nudPaginaCodigo.setValue(Integer.parseInt(ret));            

            ret = acbrSat.configLerValor(ACBrSessao.SAT, "SignAC");
            txtSignAc.setText(ret);
            
            ret = acbrSat.configLerValor(ACBrSessao.SATConfigArquivos, "SalvarCFe");
            chkSaveCFe.setSelected(!"0".equals(ret));

            ret = acbrSat.configLerValor(ACBrSessao.SATConfigArquivos, "SalvarEnvio"); 
            chkSaveEnvio.setSelected(!"0".equals(ret));  

            ret = acbrSat.configLerValor(ACBrSessao.SATConfigArquivos, "SalvarCFeCanc");
            chkSaveCFeCanc.setSelected(!"0".equals(ret));
            
            ret = acbrSat.configLerValor(ACBrSessao.SATConfigArquivos, "SepararPorCNPJ");
            chkSepararCNPJ.setSelected(!"0".equals(ret));

            ret = acbrSat.configLerValor(ACBrSessao.SATConfigArquivos, "SepararPorDia");            
            chkSepararData.setSelected(!"0".equals(ret));
            
            ret = acbrSat.configLerValor(ACBrSessao.Extrato, "Tipo");
            cmbImpressao.setSelectedItem(TipoRelatorioBobina.valueOf(Integer.parseInt(ret)));

            ret = acbrSat.configLerValor(ACBrSessao.Extrato, "Copias"); 
            nudCopias.setValue(Integer.parseInt(ret));

            ret = acbrSat.configLerValor(ACBrSessao.Sistema, "Nome");
            txtSoftwareHouse.setText(ret);
            
            ret = acbrSat.configLerValor(ACBrSessao.Extrato, "Impressora");
            cmbImpressora.setSelectedItem(ret);

            ret = acbrSat.configLerValor(ACBrSessao.Emissor, "WebSite");
            txtSite.setText(ret);
            
            ret = acbrSat.configLerValor(ACBrSessao.Extrato, "MostraPreview");            
            chkPreview.setSelected(!"0".equals(ret));
            
            ret = acbrSat.configLerValor(ACBrSessao.Extrato, "MostraSetup");
            chkSetup.setSelected(!"0".equals(ret));

            ret = acbrSat.configLerValor(ACBrSessao.Extrato, "ImprimeCodigoEan");
            chkUsaCodigoEanImpressao.setSelected(!"0".equals(ret));
            
            ret = acbrSat.configLerValor(ACBrSessao.Extrato, "ImprimeEmUmaLinha");
            chkImprimeEmUmaLinha.setSelected(!"0".equals(ret));

            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "Modelo");
            cbbModelo.setSelectedItem(ACBrPosPrinterModelo.valueOf(Integer.parseInt(ret)));
            
            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "Porta");
            cbbPortas.setSelectedItem(ret);

            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "PaginaDeCodigo");
            cbbPaginaCodigo.setSelectedItem(PosPaginaCodigo.valueOf(Integer.parseInt(ret)));            

            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "ColunasFonteNormal");
            nudColunas.setValue(Integer.parseInt(ret));

            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "EspacoEntreLinhas");
            nudEspacos.setValue(Integer.parseInt(ret));

            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "LinhasBuffer");
            nudBuffer.setValue(Integer.parseInt(ret));

            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "LinhasEntreCupons");
            nudLinhasPular.setValue(Integer.parseInt(ret));

            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "ControlePorta");            
            cbxControlePorta.setSelected(!"0".equals(ret));
            
            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "CortaPapel");
            cbxCortarPapel.setSelected(!"0".equals(ret));

            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "TraduzirTags");  
            cbxTraduzirTags.setSelected(!"0".equals(ret));

            ret = acbrSat.configLerValor(ACBrSessao.PosPrinter, "IgnorarTags");
            cbxIgnorarTags.setSelected(!"0".equals(ret));

            ret = acbrSat.configLerValor(ACBrSessao.Email, "Nome");            
            txtNome.setText(ret);
            
            ret = acbrSat.configLerValor(ACBrSessao.Email, "Conta");
            txtEmail.setText(ret);
            
            ret = acbrSat.configLerValor(ACBrSessao.Email, "Usuario");            
            txtUsuario.setText(ret);
            
            ret = acbrSat.configLerValor(ACBrSessao.Email, "Senha");
            txtSenha.setText(ret);
            
            ret = acbrSat.configLerValor(ACBrSessao.Email, "Servidor");
            txtHost.setText(ret);

            ret = acbrSat.configLerValor(ACBrSessao.Email, "Porta");
            nudPorta.setValue(Integer.parseInt(ret));

            ret = acbrSat.configLerValor(ACBrSessao.Email, "SSL");
            ckbSSL.setSelected(!"0".equals(ret));
            
            ret = acbrSat.configLerValor(ACBrSessao.Email, "TLS");
            ckbTLS.setSelected(!"0".equals(ret));
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void saveConfig(){
        try{
            acbrSat.configGravarValor(ACBrSessao.SAT, "NomeDLL", txtDllPath.getText());
            acbrSat.configGravarValor(ACBrSessao.SAT, "Modelo", ((SATModelo)cmbModeloSat.getSelectedItem()).asInt());
            acbrSat.configGravarValor(ACBrSessao.SAT, "CodigoDeAtivacao", txtAtivacao.getText());
            acbrSat.configGravarValor(ACBrSessao.SATConfig, "infCFe_versaoDadosEnt", nudVersaoCFe.getValue());
            acbrSat.configGravarValor(ACBrSessao.SATConfig, "PaginaDeCodigo", nudPaginaCodigo.getValue());
            acbrSat.configGravarValor(ACBrSessao.SAT, "SignAC", txtSignAc.getText());
            acbrSat.configGravarValor(ACBrSessao.SATConfigArquivos, "SalvarCFe", chkSaveCFe.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.SATConfigArquivos, "SalvarEnvio", chkSaveEnvio.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.SATConfigArquivos, "SalvarCFeCanc", chkSaveCFeCanc.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.SATConfigArquivos, "SepararPorCNPJ", chkSepararCNPJ.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.SATConfigArquivos, "SepararPorDia", chkSepararData.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.Extrato, "Tipo", ((TipoRelatorioBobina)cmbImpressao.getSelectedItem()).asInt());            
            acbrSat.configGravarValor(ACBrSessao.Extrato, "Copias", nudCopias.getValue());
            acbrSat.configGravarValor(ACBrSessao.Sistema, "nome", txtSoftwareHouse.getText());
            acbrSat.configGravarValor(ACBrSessao.Extrato, "Impressora", cmbImpressora.getSelectedItem().toString());
            acbrSat.configGravarValor(ACBrSessao.Emissor, "WebSite", txtSite.getText());            
            acbrSat.configGravarValor(ACBrSessao.Extrato, "MostraPreview", chkPreview.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.Extrato, "MostraSetup", chkSetup.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.Extrato, "ImprimeCodigoEan", chkUsaCodigoEanImpressao.isSelected() ? "1" : "0");            
            acbrSat.configGravarValor(ACBrSessao.Extrato, "ImprimeEmUmaLinha", chkImprimeEmUmaLinha.isSelected() ? "1" : "0");            
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "Modelo", ((ACBrPosPrinterModelo)cbbModelo.getSelectedItem()).asInt());
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "Porta", cbbPortas.getSelectedItem().toString());
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "ColunasFonteNormal", nudColunas.getValue());            
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "EspacoEntreLinhas", nudEspacos.getValue());
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "LinhasBuffer", nudBuffer.getValue());
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "LinhasEntreCupons", nudLinhasPular.getValue());            
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "ControlePorta", cbxControlePorta.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "CortaPapel", cbxCortarPapel.isSelected() ? "1" : "0");            
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "TraduzirTags", cbxTraduzirTags.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "IgnorarTags", cbxIgnorarTags.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.PosPrinter, "PaginaDeCodigo", ((PosPaginaCodigo)cbbPaginaCodigo.getSelectedItem()).asInt());
            acbrSat.configGravarValor(ACBrSessao.Email, "Nome", txtNome.getText());
            acbrSat.configGravarValor(ACBrSessao.Email, "Conta", txtEmail.getText());
            acbrSat.configGravarValor(ACBrSessao.Email, "Usuario", txtUsuario.getText());
            acbrSat.configGravarValor(ACBrSessao.Email, "Senha", new String(txtSenha.getPassword()));
            acbrSat.configGravarValor(ACBrSessao.Email, "Servidor", txtHost.getText());
            acbrSat.configGravarValor(ACBrSessao.Email, "Porta", nudPorta.getValue().toString());
            acbrSat.configGravarValor(ACBrSessao.Email, "SSL", ckbSSL.isSelected() ? "1" : "0");
            acbrSat.configGravarValor(ACBrSessao.Email, "TLS", ckbTLS.isSelected() ? "1" : "0");
            acbrSat.configGravar();            
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarSAT;
    private javax.swing.JButton btnConsultarStatus;
    private javax.swing.JButton btnCriarCFe;
    private javax.swing.JButton btnCriarEnviarCFe;
    private javax.swing.JButton btnEnviarCFe;
    private javax.swing.JButton btnImprimiCFeRed;
    private javax.swing.JButton btnImprimirCFe;
    private javax.swing.JButton btnImprimirPDFCFe;
    private javax.swing.JButton btnIniDesini;
    private javax.swing.JButton btnSelDll;
    private javax.swing.JComboBox<ACBrPosPrinterModelo> cbbModelo;
    private javax.swing.JComboBox<PosPaginaCodigo> cbbPaginaCodigo;
    private javax.swing.JComboBox<String> cbbPortas;
    private javax.swing.JCheckBox cbxControlePorta;
    private javax.swing.JCheckBox cbxCortarPapel;
    private javax.swing.JCheckBox cbxIgnorarTags;
    private javax.swing.JCheckBox cbxTraduzirTags;
    private javax.swing.JCheckBox chkImprimeEmUmaLinha;
    private javax.swing.JCheckBox chkPreview;
    private javax.swing.JCheckBox chkSaveCFe;
    private javax.swing.JCheckBox chkSaveCFeCanc;
    private javax.swing.JCheckBox chkSaveEnvio;
    private javax.swing.JCheckBox chkSepararCNPJ;
    private javax.swing.JCheckBox chkSepararData;
    private javax.swing.JCheckBox chkSetup;
    private javax.swing.JCheckBox chkUsaCodigoEanImpressao;
    private javax.swing.JCheckBox ckbSSL;
    private javax.swing.JCheckBox ckbTLS;
    private javax.swing.JComboBox<TipoRelatorioBobina> cmbImpressao;
    private javax.swing.JComboBox<String> cmbImpressora;
    private javax.swing.JComboBox<SATModelo> cmbModeloSat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner nudBuffer;
    private javax.swing.JSpinner nudColunas;
    private javax.swing.JSpinner nudCopias;
    private javax.swing.JSpinner nudEspacos;
    private javax.swing.JSpinner nudLinhasPular;
    private javax.swing.JSpinner nudPaginaCodigo;
    private javax.swing.JSpinner nudPorta;
    private javax.swing.JSpinner nudVersaoCFe;
    private javax.swing.JTextArea rtbRespostas;
    private javax.swing.JTextField txtAtivacao;
    private javax.swing.JTextField txtDllPath;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSignAc;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtSoftwareHouse;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
